import mongoose from 'mongoose';

const sessionStatusValues = [
    'created',
    'queued',
    'agent_assigned',
    'opening',
    'awaiting_user',
    'manual_action_required',
    'ready_to_capture',
    'capturing',
    'completed',
    'cancelled',
    'expired',
    'failed',
];

const assistedCaptureSessionSchema = new mongoose.Schema(
    {
        companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true, index: true },
        campaignId: { type: mongoose.Schema.Types.ObjectId, ref: 'SearchCampaign', required: true, index: true },
        queryId: { type: mongoose.Schema.Types.ObjectId, ref: 'SearchQuery', required: true, index: true },
        discoveryAgentJobId: { type: mongoose.Schema.Types.ObjectId, ref: 'DiscoveryAgentJob', default: null },
        source: { type: String, default: 'google', enum: ['google'] },
        sourceHint: { type: String, default: 'google', trim: true, maxlength: 80 },
        searchUrl: { type: String, required: true, trim: true, maxlength: 2048 },
        searchUrlHash: { type: String, required: true, trim: true, maxlength: 64 },
        status: { type: String, enum: sessionStatusValues, default: 'created', index: true },
        idempotencyKey: { type: String, default: '', trim: true, maxlength: 200 },
        requestFingerprint: { type: String, required: true, trim: true, maxlength: 64 },
        tokenHash: { type: String, required: true, trim: true, maxlength: 64 },
        tokenExpiresAt: { type: Date, required: true },
        sessionExpiresAt: { type: Date, required: true, index: true },
        tokenDeliveredAt: { type: Date, default: null },
        agentId: { type: String, default: '', trim: true, maxlength: 120 },
        browserOpenedAcked: { type: Boolean, default: false },
        openedAt: { type: Date, default: null },
        lastHeartbeatAt: { type: Date, default: null },
        lastEventAt: { type: Date, default: null },
        lastEventSequence: { type: Number, default: 0 },
        mode: { type: String, default: 'assisted_visible', trim: true, maxlength: 40 },
        browserMode: { type: String, default: 'visible', enum: ['visible'], trim: true },
        agentVersion: { type: String, default: '', trim: true, maxlength: 80 },
        totalEvents: { type: Number, default: 0 },
        captureEventCount: { type: Number, default: 0 },
        totalResults: { type: Number, default: 0 },
        totalVisibleResults: { type: Number, default: 0 },
        visibleResultCount: { type: Number, default: 0 },
        acceptedCount: { type: Number, default: 0 },
        insertedCount: { type: Number, default: 0 },
        updatedExistingCount: { type: Number, default: 0 },
        rejectedCount: { type: Number, default: 0 },
        rawCaptureBatchIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'RawCaptureBatch' }],
        firstCaptureAt: { type: Date, default: null },
        lastCaptureAt: { type: Date, default: null },
        completedAt: { type: Date, default: null },
        completedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        cancelledAt: { type: Date, default: null },
        cancelledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        failedAt: { type: Date, default: null },
        failureCode: { type: String, default: '', trim: true, maxlength: 80 },
        safeFailureMessage: { type: String, default: '', trim: true, maxlength: 500 },
        failCode: { type: String, default: '', trim: true, maxlength: 80 },
        failMessage: { type: String, default: '', trim: true, maxlength: 500 },
        manualActionMessage: { type: String, default: '', trim: true, maxlength: 500 },
        createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        // Checkpoint 5B — queued UI capture request (additive; stdin `capture` still works)
        pendingCaptureIdempotencyKey: { type: String, default: '', trim: true, maxlength: 200 },
        pendingCaptureRequestedAt: { type: Date, default: null },
        pendingCaptureRequestedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        pendingCaptureStatus: {
            type: String,
            enum: ['none', 'pending', 'acked', 'consumed'],
            default: 'none',
        },
        pendingCaptureAckedAt: { type: Date, default: null },
        // Simple Lead Search — owner-driven Google page navigation (no auto loops)
        googlePageIndex: { type: Number, default: 1, min: 1 },
        pendingNavigationStatus: {
            type: String,
            enum: ['none', 'pending', 'acked', 'consumed'],
            default: 'none',
        },
        pendingNavigationTargetUrl: { type: String, default: '', trim: true, maxlength: 2048 },
        pendingNavigationRequestedAt: { type: Date, default: null },
        pendingNavigationRequestedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        pendingNavigationAckedAt: { type: Date, default: null },
        // Optional Simple Lead Search Auto Collection (owner-started only; no Lead creation)
        autoCollection: {
            enabled: { type: Boolean, default: false },
            status: {
                type: String,
                enum: ['idle', 'running', 'paused_owner', 'paused_manual', 'paused_batch', 'stopped', 'completed', 'failed'],
                default: 'idle',
            },
            phase: {
                type: String,
                enum: [
                    'none', 'delay', 'capture', 'await_capture', 'decide_next',
                    'next_page', 'await_nav', 'complete_query', 'next_query', 'await_query_ready',
                    'enrich', 'qualify', 'await_batch_continue', 'done',
                ],
                default: 'none',
            },
            pageCollectionMode: {
                type: String,
                enum: ['fixed', 'batches', 'until_no_more'],
                default: 'fixed',
            },
            maxPagesPerQuery: { type: Number, default: 3, min: 1, max: 10 },
            pagesPerBatch: { type: Number, default: 10, min: 1, max: 10 },
            maxSafetyPagesPerQuery: { type: Number, default: 30, min: 10, max: 50 },
            pauseAfterEachBatch: { type: Boolean, default: true },
            currentBatch: { type: Number, default: 1, min: 1 },
            pagesInCurrentBatch: { type: Number, default: 0, min: 0 },
            batchStartPage: { type: Number, default: 1, min: 1 },
            lastSuccessfullyCapturedPage: { type: Number, default: 0, min: 0 },
            resumeQueryId: { type: mongoose.Schema.Types.ObjectId, ref: 'SearchQuery', default: null },
            resumeQueryIndex: { type: Number, default: 1, min: 1 },
            resumeMessage: { type: String, default: '', maxlength: 300 },
            batchMessage: { type: String, default: '', maxlength: 500 },
            maxQueries: { type: Number, default: 3, min: 1, max: 24 },
            delayMinSec: { type: Number, default: 20, min: 5, max: 120 },
            delayMaxSec: { type: Number, default: 40, min: 5, max: 180 },
            stopAtUnique: { type: Number, default: 0, min: 0 },
            stopOnNoNewUniquePages: { type: Boolean, default: true },
            autoEnrichAfter: { type: Boolean, default: false },
            autoQualifyAfterEnrich: { type: Boolean, default: false },
            autoVerifyAfterQualify: { type: Boolean, default: false },
            nextActionAt: { type: Date, default: null },
            tickLockUntil: { type: Date, default: null },
            pagesCapturedThisQuery: { type: Number, default: 0 },
            pagesProcessedTotal: { type: Number, default: 0 },
            queriesProcessedTotal: { type: Number, default: 0 },
            consecutiveNoNewPages: { type: Number, default: 0 },
            uniqueAtStart: { type: Number, default: 0 },
            uniqueBeforeLastCapture: { type: Number, default: 0 },
            lastPageVisible: { type: Number, default: 0 },
            lastPageNewUnique: { type: Number, default: 0 },
            lastPageUpdated: { type: Number, default: 0 },
            captureEventsAtLastRequest: { type: Number, default: 0 },
            insertedAtLastRequest: { type: Number, default: 0 },
            updatedAtLastRequest: { type: Number, default: 0 },
            summary: {
                pagesProcessed: { type: Number, default: 0 },
                queriesProcessed: { type: Number, default: 0 },
                totalAppearances: { type: Number, default: 0 },
                newUniqueResults: { type: Number, default: 0 },
                existingUpdated: { type: Number, default: 0 },
                rejectedUnwanted: { type: Number, default: 0 },
                finalCampaignUnique: { type: Number, default: 0 },
                stopReason: { type: String, default: '', maxlength: 120 },
            },
            lastErrorCode: { type: String, default: '', maxlength: 80 },
            lastErrorMessage: { type: String, default: '', maxlength: 500 },
            startedAt: { type: Date, default: null },
            stoppedAt: { type: Date, default: null },
            startedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
            stoppedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
            rootSessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'AssistedCaptureSession', default: null },
            campaignId: { type: mongoose.Schema.Types.ObjectId, ref: 'SearchCampaign', default: null },
        },
        autoProcessing: {
            enabled: { type: Boolean, default: false },
            /** Owner one-click / enable workflow — survives idle; cleared only by Stop All */
            ownerWorkflowEnabled: { type: Boolean, default: false },
            status: {
                type: String,
                enum: ['idle', 'running', 'paused_owner', 'stopped', 'completed', 'failed'],
                default: 'idle',
            },
            batchSize: { type: Number, default: 10, min: 1, max: 100 },
            autoEnrich: { type: Boolean, default: true },
            autoQualify: { type: Boolean, default: true },
            autoVerify: { type: Boolean, default: true },
            continueWhileCollecting: { type: Boolean, default: true },
            retryTemporaryFailures: { type: Boolean, default: true },
            maxRetryAttempts: { type: Number, default: 2, min: 0, max: 5 },
            autoCreateCrmLeads: { type: Boolean, default: false }, // permanently off
            autoResumeNotice: { type: Boolean, default: false },
            currentStage: {
                type: String,
                enum: ['idle', 'waiting_batch', 'enriching', 'qualifying', 'verifying', 'flushing', 'done'],
                default: 'idle',
            },
            currentBatchNumber: { type: Number, default: 0, min: 0 },
            currentBatchCaptureIds: { type: [mongoose.Schema.Types.ObjectId], default: [] },
            currentBatchEnrichmentIds: { type: [mongoose.Schema.Types.ObjectId], default: [] },
            currentBatchQualificationIds: { type: [mongoose.Schema.Types.ObjectId], default: [] },
            currentEnrichJobId: { type: mongoose.Schema.Types.ObjectId, default: null },
            currentQualifyJobId: { type: mongoose.Schema.Types.ObjectId, default: null },
            currentVerifyJobId: { type: mongoose.Schema.Types.ObjectId, default: null },
            processedCaptureIdKeys: { type: [String], default: [] }, // capped list of processed capture ids
            flushRequested: { type: Boolean, default: false },
            stopCaptureOnly: { type: Boolean, default: false },
            tickLockUntil: { type: Date, default: null },
            lastTickAt: { type: Date, default: null },
            lastProcessedAt: { type: Date, default: null },
            retryCount: { type: Number, default: 0, min: 0 },
            lastErrorCode: { type: String, default: '', maxlength: 80 },
            lastErrorMessage: { type: String, default: '', maxlength: 500 },
            counts: {
                capturedUnique: { type: Number, default: 0 },
                waitingEnrichment: { type: Number, default: 0 },
                enriching: { type: Number, default: 0 },
                enriched: { type: Number, default: 0 },
                noWebsite: { type: Number, default: 0 },
                enrichmentFailed: { type: Number, default: 0 },
                waitingQualification: { type: Number, default: 0 },
                qualified: { type: Number, default: 0 },
                rejected: { type: Number, default: 0 },
                waitingVerification: { type: Number, default: 0 },
                verified: { type: Number, default: 0 },
                verificationFailed: { type: Number, default: 0 },
                reviewRequired: { type: Number, default: 0 },
                failed: { type: Number, default: 0 },
                processingBacklog: { type: Number, default: 0 },
                batchesCompleted: { type: Number, default: 0 },
                // Mutually exclusive per-capture buckets (sum === capturedUnique)
                reconcileWaiting: { type: Number, default: 0 },
                reconcileProcessing: { type: Number, default: 0 },
                reconcileCompleted: { type: Number, default: 0 },
                reconcileReviewRequired: { type: Number, default: 0 },
                reconcileRejectedSkipped: { type: Number, default: 0 },
                reconcileFailed: { type: Number, default: 0 },
                stageEnrichmentDocs: { type: Number, default: 0 },
                stageQualificationDocs: { type: Number, default: 0 },
                stageGenuinenessDocs: { type: Number, default: 0 },
            },
            lastBatchStartedAt: { type: Date, default: null },
            lastBatchCompletedAt: { type: Date, default: null },
            nextRetryAt: { type: Date, default: null },
            startedAt: { type: Date, default: null },
            stoppedAt: { type: Date, default: null },
            startedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
            stoppedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
            rootSessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'AssistedCaptureSession', default: null },
            campaignId: { type: mongoose.Schema.Types.ObjectId, ref: 'SearchCampaign', default: null },
        },
    },
    { timestamps: true, collection: 'assisted_capture_sessions' },
);

assistedCaptureSessionSchema.index({ companyId: 1, campaignId: 1, queryId: 1, createdAt: -1 });
assistedCaptureSessionSchema.index({ companyId: 1, status: 1, createdAt: 1 });
assistedCaptureSessionSchema.index({ companyId: 1, agentId: 1, status: 1 });
assistedCaptureSessionSchema.index(
    { companyId: 1, idempotencyKey: 1 },
    {
        unique: true,
        partialFilterExpression: { idempotencyKey: { $exists: true, $ne: '' } },
    },
);

const AssistedCaptureSession = mongoose.models.AssistedCaptureSession
    || mongoose.model('AssistedCaptureSession', assistedCaptureSessionSchema);

export { AssistedCaptureSession, sessionStatusValues as ASSISTED_CAPTURE_SESSION_STATUSES };
export default AssistedCaptureSession;
