export const PATHS = {
    ROOT: '/',
    DASHBOARD: '/',
    CUSTOMERS: {
        ROOT: '/customers',
        LIST: '/customers/list',
        ADD: '/customers/add',
        DETAILS: (id) => `/customers/${id}`,
    },
    REMINDERS: {
        ROOT: '/reminders',
    },
    REPORTS: {
        ROOT: '/reports',
        CUSTOMER_MASTER: '/reports/customer-master',
        CONSUMABLE_COST: '/reports/consumable-cost',
        PRODUCT_GP: '/reports/product-gp',
        REPLACEMENTS: '/reports/replacements',
        SAMPLE_CONVERSION: '/reports/sample-conversion',
    },
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
    },
    SETTINGS: {
        ROOT: '/admin',
        HOME: '/admin/home',
        COMPANY_PROFILE: '/company-profile',
        WHATSAPP: '/whatsapp',
    },
    GROUPS: {
        ROOT: '/groups',
        DETAILS: (id) => `/groups/${id}`,
    },
    TASKS: {
        GROUPS: '/tasks/groups',
    },
    INVENTORY: {
        ROOT: '/inventory',
        HOME: '/inventory/home',
        ITEMS: '/inventory/items',
        NEW_ITEM: '/inventory/items/new',
        EDIT_ITEM: (id) => `/inventory/items/${id}`,
        ITEM_TYPES: '/inventory/item-types',
        ITEM_GROUPS: '/inventory/item-groups',
        BOM: {
            ROOT: '/inventory/bom',
            NEW: '/inventory/bom/new',
            EDIT: (id) => `/inventory/bom/edit/${id}`,
        },
    },
    PRODUCTION: {
        ROOT: '/production',
        HOME: '/production/home',
        DASHBOARD: '/production',
        WORK_ORDERS: '/production/work-orders',
        NEW_WO: '/production/work-orders/new',
        WO_DETAIL: (id) => `/production/work-orders/${id}`,
        PLANNING: {
            ROOT: '/production/planning',
            NEW: '/production/planning/new',
            DETAILS: (id) => `/production/planning/${id}`,
        }
    },
    PURCHASE: {
        ROOT: '/purchase',
        HOME: '/purchase/home',
        SUPPLIERS: '/purchase/suppliers',
        ORDERS: '/purchase/orders',
        NEW_ORDER: '/purchase/orders/new',
        EDIT_ORDER: (id) => `/purchase/orders/edit/${id}`,
        ORDER_DETAIL: (id) => `/purchase/orders/${id}`,
        GRN: '/purchase/grn',
        GRN_NEW: '/purchase/grn/new',
        GRN_DETAIL: (id) => `/purchase/grn/${id}`,
        INVOICES: '/purchase/invoices',
        NEW_INVOICE: '/purchase/invoices/new',
        EDIT_INVOICE: (id) => `/purchase/invoices/edit/${id}`,
        INVOICE_DETAIL: (id) => `/purchase/invoices/${id}`,
        PURCHASE_REPORT: '/reports/purchase-comparison',
    },
    SALES: {
        ROOT: '/sales',
        HOME: '/sales/home',
        DASHBOARD: '/sales',
        ORDERS: '/sales/orders',
        NEW_ORDER: '/sales/orders/new',
        ORDER_DETAIL: (id) => `/sales/orders/${id}`,
        INVOICES: '/sales/invoices',
        NEW_INVOICE: '/sales/invoices/new',
        INVOICE_DETAIL: (id) => `/sales/invoices/${id}`,
        PRODUCTION_SHEET: (id) => `/sales/production-sheets/${id}`,
        INVOICE_SERIES: '/sales/invoice-series',
        INVOICE_CLEANUP: '/sales/invoice-cleanup',
        RESEQUENCE_TOOL: '/sales/invoice-resequence',
        BULK_RENUMBER: '/sales/bulk-renumber',
        CREDIT_NOTES: '/sales/credit-notes',
        DEBIT_NOTES: '/sales/debit-notes',
        CREDIT_NOTE_DETAIL: (id) => `/sales/credit-notes/${id}`,
        DEBIT_NOTE_DETAIL: (id) => `/sales/credit-notes/${id}`,
    },
    SERVICE: {
        ROOT: '/service',
        HOME: '/service/home',
        COMPLAINTS: '/service/complaints',
        REPLACEMENT_DASHBOARD: '/service/replacement-dashboard',
    },
    PRD: {
        ROOT: '/prd',
        HOME: '/prd/home',
        PROJECTS: '/prd/projects',
        DASHBOARD: '/prd/dashboard',
        TEST_PARAMETERS: '/prd/test-parameters',
    },
    ACCOUNT_MASTER: {
        ROOT: '/account-master',
        HOME: '/account-master/home',
        GROUP_MASTER: '/account-master/groups',
        LEDGER_MASTER: '/account-master/ledgers',
        FINANCIAL_YEAR: '/account-master/financial-years',
        SERIES_MASTER: '/account-master/series',
    },
    ACCOUNTS: {
        ROOT: '/accounts',
        HOME: '/accounts/home',
        RECEIPT_ENTRY: '/accounts/receipt-entry',
        PAYMENT_ENTRY: '/accounts/payment-entry',
        EXPENSE_ENTRY: '/accounts/expense-entry',
        JOURNAL_ENTRY: '/accounts/journal-entry',
        CREDIT_NOTES: '/voucher-entry/credit-notes',
        DEBIT_NOTES: '/voucher-entry/debit-notes',
        CREDIT_NOTE_DETAIL: (id) => `/voucher-entry/credit-notes/${id}`,
        DEBIT_NOTE_DETAIL: (id) => `/voucher-entry/debit-notes/${id}`,
        CREDIT_NOTE_DETAIL_PATTERN: '/voucher-entry/credit-notes/:id',
        DEBIT_NOTE_DETAIL_PATTERN: '/voucher-entry/debit-notes/:id',
        VOUCHER_LIST: '/accounts/vouchers',
        CASH_BANK_MASTER: '/accounts/masters/cash-bank',
        GROUP_MASTER: '/accounts/masters/groups',
        LEDGER_MASTER: '/accounts/masters/ledgers',
        VOUCHER_TYPE_MASTER: '/accounts/masters/voucher-types',
        FINANCIAL_YEAR: '/accounts/masters/financial-years',
        LEDGER_REPORT: '/accounts/reports/ledger',
        SALES_REGISTER: '/accounts/reports/sales-register',
        PURCHASE_REGISTER: '/accounts/reports/purchase-register',
        EXPENSE_REGISTER: '/accounts/reports/expense-register',
        DAY_BOOK: '/accounts/reports/day-book',
        CASH_BOOK: '/accounts/reports/cash-book',
        BANK_BOOK: '/accounts/reports/bank-book',
        OUTSTANDING_REPORT: '/accounts/reports/outstanding',
    },
    FIXED_ASSETS: {
        ROOT: '/fixed-assets',
        HOME: '/fixed-assets/home',
        LIST: '/fixed-assets/list',
        CATEGORIES: '/fixed-assets/categories',
        LOCATIONS: '/fixed-assets/locations',
    },
    MIS: {
        ROOT: '/mis',
        HOME: '/mis/home',
        SALES_DASHBOARD: '/mis/sales-dashboard',
        PRODUCT_GP: '/mis/product-gp-analysis',
        SALES_CONVERSION: '/mis/sales-conversion',
        DASHBOARD: '/mis/dashboard'
    },
    HR: {
        ROOT: '/hr',
        HOME: '/hr/home',
        DASHBOARD: '/hr/dashboard',
        EMPLOYEES: '/hr/employees',
        SHIFTS: '/hr/shifts',
        ATTENDANCE: '/hr/attendance',
        ATTENDANCE_IMPORT: '/hr/attendance/import',
        LEAVES: '/hr/leaves',
        PAYROLL: '/hr/payroll',
        REPORTS: '/hr/reports',
    },
    MESSENGER: {
        ROOT: '/messenger',
        HOME: '/messenger/home',
        THREAD: (id) => `/messenger/${id}`,
    },
    RD_SAMPLES: {
        ROOT: '/rd-samples',
        HOME: '/rd-samples/home',
        PROJECTS: '/rd-samples/projects',
        SAMPLES: '/rd-samples/samples',
        COMPARISON: '/rd-samples/comparison',
    },
    WECHAT: {
        ROOT: '/wechat',
        HOME: '/wechat/home',
        CONTACTS: '/wechat/contacts',
    },
    CHINA_SUPPLIER: {
        ROOT: '/china-supplier',
        HOME: '/china-supplier/home',
        DASHBOARD: '/china-supplier/dashboard',
        PRODUCTS: '/china-supplier/products',
        CONTACTS: '/china-supplier/contacts',
        GROUPS: '/china-supplier/groups',
        PRICES: '/china-supplier/prices',
        SAMPLES: '/china-supplier/samples',
        REPORTS: '/china-supplier/reports',
    },
    EWAY_BILL: {
        ROOT: '/eway-bills',
        HOME: '/eway-bills/home',
        LIST: '/eway-bills/list',
        DRAFT: (id) => `/eway-bills/draft/${id}`,
    },
    TRANSPORTERS: {
        ROOT: '/transporters',
        HOME: '/transporters/home',
        LIST: '/transporters/list',
    },
    GST: {
        ROOT: '/gst',
        HOME: '/gst/home'
    },
    VOUCHER_ENTRY: {
        ROOT: '/voucher-entry',
        HOME: '/voucher-entry/home'
    },
    CRM: {
        ROOT: '/crm',
        HOME: '/crm/home'
    }
};
