export const PATHS = {
    ROOT: '/',
    DASHBOARD: '/dashboard',
    CUSTOMERS: {
        ROOT: '/customers',
        LIST: '/customers/list',
        ADD: '/customers/add',
        DETAILS: (id) => `/customers/${id}`,
    },
    REMINDERS: {
        ROOT: '/reminders',
    },
    REPORTS: {
        ROOT: '/reports',
        CUSTOMER_MASTER: '/reports/customer-master',
    },
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
    },
    SETTINGS: {
        COMPANY_PROFILE: '/company-profile',
        WHATSAPP: '/settings/whatsapp',
    },
    GROUPS: {
        ROOT: '/groups',
        DETAILS: (id) => `/groups/${id}`,
    },
    TASKS: {
        GROUPS: '/tasks/groups',
    },
    INVENTORY: {
        ITEMS: '/inventory/items',
        NEW_ITEM: '/inventory/items/new',
        EDIT_ITEM: (id) => `/inventory/items/${id}`,
        ITEM_TYPES: '/inventory/item-types',
        ITEM_GROUPS: '/inventory/item-groups',
        BOM: {
            ROOT: '/inventory/bom',
            NEW: '/inventory/bom/new',
            EDIT: (id) => `/inventory/bom/edit/${id}`,
        },
    },
    PRODUCTION: {
        DASHBOARD: '/production',
        WORK_ORDERS: '/production/work-orders',
        NEW_WO: '/production/work-orders/new',
        WO_DETAIL: (id) => `/production/work-orders/${id}`,
        PLANNING: {
            ROOT: '/production/planning',
            NEW: '/production/planning/new',
            DETAILS: (id) => `/production/planning/${id}`,
        }
    },
    PURCHASE: {
        SUPPLIERS: '/purchase/suppliers',
        ORDERS: '/purchase/orders',
        NEW_ORDER: '/purchase/orders/new',
        EDIT_ORDER: (id) => `/purchase/orders/edit/${id}`,
        ORDER_DETAIL: (id) => `/purchase/orders/${id}`,
        GRN: '/purchase/grn',
        GRN_NEW: '/purchase/grn/new',
        GRN_DETAIL: (id) => `/purchase/grn/${id}`,
        INVOICES: '/purchase/invoices',
        NEW_INVOICE: '/purchase/invoices/new',
        EDIT_INVOICE: (id) => `/purchase/invoices/edit/${id}`,
        INVOICE_DETAIL: (id) => `/purchase/invoices/${id}`,
        PURCHASE_REPORT: '/reports/purchase-comparison',
    },
    SALES: {
        DASHBOARD: '/sales',
        ORDERS: '/sales/orders',
        NEW_ORDER: '/sales/orders/new',
        ORDER_DETAIL: (id) => `/sales/orders/${id}`,
        INVOICES: '/sales/invoices',
        NEW_INVOICE: '/sales/invoices/new',
        INVOICE_DETAIL: (id) => `/sales/invoices/${id}`,
        PRODUCTION_SHEET: (id) => `/sales/production-sheets/${id}`,
        INVOICE_SERIES: '/sales/invoice-series',
        INVOICE_CLEANUP: '/sales/invoice-cleanup',
        RESEQUENCE_TOOL: '/sales/invoice-resequence',
        BULK_RENUMBER: '/sales/bulk-renumber',
    },
    SERVICE: {
        COMPLAINTS: '/service/complaints',
        REPLACEMENT_DASHBOARD: '/service/replacement-dashboard',
    },
    PRD: {
        ROOT: '/prd',
        PROJECTS: '/prd/projects',
        DASHBOARD: '/prd/dashboard',
        TEST_PARAMETERS: '/prd/test-parameters',
    },
    ACCOUNTS: {
        ROOT: '/accounts',
        RECEIPT_ENTRY: '/accounts/receipt-entry',
        PAYMENT_ENTRY: '/accounts/payment-entry',
        EXPENSE_ENTRY: '/accounts/expense-entry',
        JOURNAL_ENTRY: '/accounts/journal-entry',
        VOUCHER_LIST: '/accounts/vouchers',
        CASH_BANK_MASTER: '/accounts/masters/cash-bank',
        GROUP_MASTER: '/accounts/masters/groups',
        LEDGER_MASTER: '/accounts/masters/ledgers',
        VOUCHER_TYPE_MASTER: '/accounts/masters/voucher-types',
        FINANCIAL_YEAR: '/accounts/masters/financial-years',
        LEDGER_REPORT: '/accounts/reports/ledger',
        SALES_REGISTER: '/accounts/reports/sales-register',
        PURCHASE_REGISTER: '/accounts/reports/purchase-register',
        DAY_BOOK: '/accounts/reports/day-book',
        CASH_BOOK: '/accounts/reports/cash-book',
        BANK_BOOK: '/accounts/reports/bank-book',
        OUTSTANDING_REPORT: '/accounts/reports/outstanding',
        FIXED_ASSETS: '/accounts/fixed-assets',
        ASSET_CATEGORIES: '/accounts/asset-categories',
        ASSET_LOCATIONS: '/accounts/asset-locations',
    },
    HR: {
        ROOT: '/hr',
        DASHBOARD: '/hr/dashboard',
        EMPLOYEES: '/hr/employees',
        SHIFTS: '/hr/shifts',
        ATTENDANCE: '/hr/attendance',
        ATTENDANCE_IMPORT: '/hr/attendance/import',
        LEAVES: '/hr/leaves',
        PAYROLL: '/hr/payroll',
        REPORTS: '/hr/reports',
    },
    MESSENGER: {
        ROOT: '/messenger',
        THREAD: (id) => `/messenger/${id}`,
    },
    RD_SAMPLES: {
        ROOT: '/rd-samples',
        PROJECTS: '/rd-samples/projects',
        SAMPLES: '/rd-samples/samples',
        COMPARISON: '/rd-samples/comparison',
    },
    WECHAT: {
        ROOT: '/wechat',
        CONTACTS: '/wechat/contacts',
    },
    EWAY_BILL: {
        ROOT: '/eway-bills',
        LIST: '/eway-bills/list',
        DRAFT: (id) => `/eway-bills/draft/${id}`,
    },
    TRANSPORTERS: {
        ROOT: '/transporters',
        LIST: '/transporters/list',
    }
};


