import mongoose from 'mongoose';
import { PurchaseOrder } from '../src/models/purchaseOrder.model.js';
import { Supplier } from '../src/models/supplier.model.js';
import { User } from '../src/models/user.model.js';
import { AuditLog } from '../src/models/auditLog.model.js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(process.cwd(), '.env') });

async function run() {
    try {
        await mongoose.connect(process.env.MONGODB_URL);
        console.log('Connected to DB...');

        const user = await User.findOne({});
        const supplier = await Supplier.findOne({});
        
        if (!user || !supplier) {
            console.log('Missing User or Supplier. Please ensure they exist.');
            process.exit(1);
        }

        console.log('Deleting existing POs...');
        await PurchaseOrder.deleteMany({});

        const pos = [];
        const types = ['Ordered', 'Partially Received', 'Fully Received', 'Completed'];
        
        for (let i = 1; i <= 50; i++) {
            const isDeleted = i > 45; // 5 deleted records
            const po = {
                poNumber: `PO-2026-${String(i).padStart(5, '0')}`,
                poDate: new Date(Date.now() - i * 24 * 60 * 60 * 1000),
                supplierId: supplier._id,
                supplierName: supplier.supplierName,
                status: types[i % types.length],
                items: [
                    {
                        itemId: new mongoose.Types.ObjectId(), // Stub
                        itemName: 'Raw Material ' + i,
                        orderedQty: 100,
                        receivedQty: i > 25 ? 100 : 0,
                        rate: 510 + i,
                        taxableAmount: 5100,
                        gstRate: 18,
                        taxAmount: 918,
                        totalAmount: 6018
                    }
                ],
                subTotal: 5100,
                totalTax: 918,
                grandTotal: 6018,
                createdBy: user._id,
                isDeleted: isDeleted,
                deletedAt: isDeleted ? new Date() : null,
                deletedBy: isDeleted ? user._id : null,
                deleteReason: isDeleted ? 'Order cancelled by supplier' : ''
            };
            pos.push(po);
        }

        console.log('Inserting 50 POs...');
        const result = await PurchaseOrder.insertMany(pos);
        
        // Add audit logs for some
        const auditLogs = result.slice(0, 5).map(r => ({
            user: user._id,
            action: 'CREATE',
            module: 'PurchaseOrder',
            resourceId: r._id,
            description: `Auto-generated Purchase Order ${r.poNumber}`,
            details: { autoGenerated: true }
        }));
        await AuditLog.insertMany(auditLogs);

        console.log('Done! 50 Purchase Orders created.');
    } catch (err) {
        console.error('ERROR:', err);
    } finally {
        await mongoose.disconnect();
    }
}

run();
