/** Placeholder document data for layout-only WYSIWYG preview (not saved to format). */
export function buildLayoutPreviewDocument(docType) {
    const now = new Date().toISOString();
    if (docType === 'Sales Order') {
        return {
            _layoutPreview: true,
            soNumber: '26-27/069',
            soDate: now,
            deliveryDate: now,
            customerPO: 'VERBAL',
            customerName: 'Sample Customer Pvt Ltd',
            billingAddress: '123 Sample Street, Andheri East, Mumbai - 400069, Maharashtra',
            shippingAddress: '123 Sample Street, Andheri East, Mumbai - 400069, Maharashtra',
            customerGstin: '27AAAAA0000A1Z5',
            gstApplicable: true,
            orderCategory: 'Order',
            items: [
                {
                    itemCode: 'JU-001',
                    description: 'SAMPLE PRODUCT A',
                    additionalNotes: '—',
                    hsnCode: '8504',
                    uom: 'NOS',
                    qty: 2,
                    rate: 1500,
                    amount: 3000,
                },
                {
                    itemCode: 'JU-002',
                    description: 'SAMPLE PRODUCT B',
                    additionalNotes: 'Layout preview',
                    hsnCode: '8504',
                    uom: 'NOS',
                    qty: 1,
                    rate: 2500,
                    amount: 2500,
                },
            ],
            subtotal: 5500,
            totalAmount: 5500,
            totalTaxableAmount: 5500,
            totalCgst: 495,
            totalSgst: 495,
            totalGst: 990,
            gstType: 'CGST_SGST',
            freightAmount: 0,
            roundOff: 0,
            grandTotal: 6490,
            roundedTotal: 6490,
            amountInWords: 'Six Thousand Four Hundred Ninety',
            remarks: 'Sample remarks — layout preview only.',
        };
    }
    return {
        _layoutPreview: true,
        invoiceNumber: '26-27/001',
        displayInvoiceNumber: '26-27/001',
        invoiceDate: now,
        dueDate: now,
        customerName: 'Sample Customer Pvt Ltd',
        billingAddress: '123 Sample Street, Mumbai, Maharashtra',
        shippingAddress: '123 Sample Street, Mumbai, Maharashtra',
        placeOfSupply: 'Maharashtra',
        gstApplicable: true,
        items: [
            {
                itemCode: 'JU-001',
                description: 'SAMPLE ITEM',
                hsnCode: '8504',
                uom: 'NOS',
                qty: 1,
                rate: 5000,
                taxableAmount: 5000,
            },
        ],
        totalTaxableAmount: 5000,
        taxableAmount: 5000,
        totalCgst: 450,
        totalSgst: 450,
        totalTaxAmount: 900,
        gstType: 'CGST_SGST',
        freightAmount: 0,
        roundOff: 0,
        amountInWords: 'Five Thousand Nine Hundred',
        grandTotal: 5900,
        roundedTotal: 5900,
        remarks: 'Sample invoice — layout preview only.',
    };
}
