import React from 'react';
import ExpandableModuleHome from '@/features/dashboard/components/ExpandableModuleHome';
import {
    Percent,
    Receipt,
    FileText,
    Scale,
    BookOpen,
    LayoutDashboard,
    Settings2,
    Wallet,
    ScrollText,
} from 'lucide-react';
import { PATHS } from '@/routes/paths';

const SESSION_SECTION_KEY = 'jsk.taxationHome.expandedSection';

const SECTIONS = [
    {
        id: 'gst',
        title: 'GST',
        description: 'GSTR-1, GSTR-3B, ITC, HSN and GST ledgers.',
        icon: Percent,
        expandedHeading: 'GST Tools',
        moduleCode: 'gst',
        tools: [
            {
                id: 'gstr1-export',
                title: 'GSTR-1 Compliance',
                description: 'Prepare and review GSTR-1 returns.',
                path: PATHS.GST.GSTR1,
                icon: FileText,
                permission: 'gst.gstr1.view',
                moduleCode: 'gst',
            },
            {
                id: 'gstr3b-compliance',
                title: 'GSTR-3B Compliance',
                description: 'Prepare and review GSTR-3B returns.',
                path: PATHS.GST.GSTR3B,
                icon: FileText,
                permission: 'gst.gstr3b.view',
                moduleCode: 'gst',
            },
            {
                id: 'gstr9-annual',
                title: 'GSTR-9 Annual Return',
                description: 'Annual GST return workspace.',
                path: PATHS.GST.GSTR9,
                icon: ScrollText,
                permission: 'gst.gstr3b.view',
                moduleCode: 'gst',
            },
            {
                id: 'gst-reconciliation',
                title: '2A / 2B Reconciliation',
                description: 'Reconcile GSTR-2A / 2B with books.',
                path: PATHS.GST.RECONCILIATION,
                icon: Scale,
                permission: 'gst.gst_reconciliation.view',
                moduleCode: 'gst',
            },
            {
                id: 'itc-register',
                title: 'GST Inward & ITC Register',
                description: 'Inward supplies and ITC tracking.',
                path: PATHS.GST.ITC_REGISTER,
                icon: BookOpen,
                permission: 'gst.itc_register.view',
                moduleCode: 'gst',
            },
            {
                id: 'gst-payable',
                title: 'GST Payable Summary',
                description: 'GST liability summary.',
                path: PATHS.GST.PAYABLE,
                icon: Wallet,
                permission: 'gst.gst_payable.view',
                moduleCode: 'gst',
            },
            {
                id: 'hsn-summary',
                title: 'HSN Summary',
                description: 'HSN-wise tax summary.',
                path: PATHS.GST.HSN_SUMMARY,
                icon: FileText,
                permission: 'gst.hsn_summary.view',
                moduleCode: 'gst',
            },
            {
                id: 'gst-ledger',
                title: 'GST Ledger',
                description: 'GST ledger balances and movements.',
                path: PATHS.GST.LEDGER,
                icon: BookOpen,
                permission: 'gst.gst_ledger.view',
                moduleCode: 'gst',
            },
        ],
    },
    {
        id: 'tds',
        title: 'TDS',
        description: 'Deduction register, challan, returns and TDS reports.',
        icon: Receipt,
        expandedHeading: 'TDS Tools',
        moduleCode: 'tds',
        tools: [
            {
                id: 'tds-dashboard',
                title: 'TDS Dashboard',
                description: 'TDS compliance overview.',
                path: PATHS.TDS.DASHBOARD,
                icon: LayoutDashboard,
                permission: 'tds.dashboard.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-master',
                title: 'TDS Master / Section Rates',
                description: 'Sections and rate master.',
                path: PATHS.TDS.MASTER,
                icon: Settings2,
                permission: 'tds.master.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-ledger-mapping',
                title: 'TDS Ledger Mapping',
                description: 'Map TDS ledgers to sections.',
                path: PATHS.TDS.LEDGER_MAPPING,
                icon: BookOpen,
                permission: 'tds.ledger_mapping.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-deduction-register',
                title: 'TDS Deduction Register',
                description: 'Recorded TDS deductions.',
                path: PATHS.TDS.DEDUCTIONS,
                icon: Receipt,
                permission: 'tds.deduction_register.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-payable-register',
                title: 'TDS Payable Register',
                description: 'TDS payable outstanding.',
                path: PATHS.TDS.PAYABLE_REGISTER,
                icon: Wallet,
                permission: 'tds.payable_register.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-challan',
                title: 'TDS Challan / Payment',
                description: 'Challan entry and payments.',
                path: PATHS.TDS.CHALLANS,
                icon: FileText,
                permission: 'tds.challan.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-returns',
                title: 'TDS Return / Filing Data',
                description: 'Return preparation data.',
                path: PATHS.TDS.RETURNS,
                icon: ScrollText,
                permission: 'tds.returns.view',
                moduleCode: 'tds',
            },
            {
                id: 'tds-reports',
                title: 'TDS Reports',
                description: 'TDS reporting suite.',
                path: PATHS.TDS.REPORTS,
                icon: FileText,
                permission: 'tds.reports.view',
                moduleCode: 'tds',
            },
            {
                id: 'form-26as',
                title: '26AS Reconciliation',
                description: 'Reconcile Form 26AS.',
                path: PATHS.FORM_26AS.LIST,
                icon: Scale,
                permission: 'tds.reports.view',
                moduleCode: 'tds',
            },
        ],
    },
    {
        id: 'tcs',
        title: 'TCS',
        description: 'Collection register, challan and TCS reports.',
        icon: Receipt,
        expandedHeading: 'TCS Tools',
        moduleCode: 'tcs',
        tools: [
            {
                id: 'tcs-dashboard',
                title: 'TCS Dashboard',
                description: 'TCS compliance overview.',
                path: PATHS.TCS.DASHBOARD,
                icon: LayoutDashboard,
                permission: 'tds.dashboard.view',
                moduleCode: 'tcs',
            },
            {
                id: 'tcs-master',
                title: 'TCS Master / Section Rates',
                description: 'Sections and rate master.',
                path: PATHS.TCS.MASTER,
                icon: Settings2,
                permission: 'tds.master.view',
                moduleCode: 'tcs',
            },
            {
                id: 'tcs-deductions',
                title: 'TCS Deduction Register',
                description: 'Recorded TCS collections.',
                path: PATHS.TCS.DEDUCTIONS,
                icon: Receipt,
                permission: 'tds.deduction_register.view',
                moduleCode: 'tcs',
            },
            {
                id: 'tcs-challans',
                title: 'TCS Challan / Payment',
                description: 'Challan entry and payments.',
                path: PATHS.TCS.CHALLANS,
                icon: FileText,
                permission: 'tds.challan.view',
                moduleCode: 'tcs',
            },
            {
                id: 'tcs-reports',
                title: 'TCS Reports',
                description: 'TCS reporting suite.',
                path: PATHS.TCS.REPORTS,
                icon: FileText,
                permission: 'tds.reports.view',
                moduleCode: 'tcs',
            },
        ],
    },
];

export default function TaxationHomePage() {
    return (
        <ExpandableModuleHome
            title="Taxation - Home"
            subtitle="Manage GST, TDS and TCS compliance reports and returns."
            sections={SECTIONS}
            sessionKey={SESSION_SECTION_KEY}
            dataComponent="taxation-home"
        />
    );
}
