import React from 'react';
import ExpandableModuleHome from '@/features/dashboard/components/ExpandableModuleHome';
import {
    MessageSquare,
    Bot,
    Megaphone,
    Settings,
    LayoutDashboard,
    Inbox,
    MessagesSquare,
    UserRound,
    FileText,
    Reply,
    BookOpen,
    FileStack,
    SlidersHorizontal,
    ScrollText,
    MessageCircle,
    Ban,
    History,
    HeartPulse,
} from 'lucide-react';
import { PATHS } from '@/routes/paths';
import { WHATSAPP_AI_FEATURE, WHATSAPP_AI_PERMISSIONS } from '@/features/whatsappAi/constants';

const SESSION_SECTION_KEY = 'jsk.whatsappHome.expandedSection';

const SECTIONS = [
    {
        id: 'communication',
        title: 'Communication',
        description: 'Manage chats, contacts, templates and communication history.',
        icon: MessageSquare,
        expandedHeading: 'Communication Tools',
        tools: [
            {
                id: 'whatsapp-chat',
                title: 'Chats',
                description: 'Open WhatsApp conversations and message history.',
                path: '/whatsapp/chat',
                icon: MessageCircle,
                permission: 'whatsapp.whatsapp_settings.view',
                moduleCode: 'whatsapp',
            },
        ],
    },
    {
        id: 'ai',
        title: 'AI Assistant',
        description: 'Manage AI conversations, inbox, drafts, automation and human handover.',
        icon: Bot,
        expandedHeading: 'AI Assistant Tools',
        featurePath: WHATSAPP_AI_FEATURE,
        moduleCode: 'whatsapp_ai',
        tools: [
            {
                id: 'communication-whatsapp-ai-dashboard',
                title: 'Dashboard',
                description: 'Overview and analytics',
                path: PATHS.SETTINGS.WHATSAPP_AI.DASHBOARD,
                icon: LayoutDashboard,
                permission: WHATSAPP_AI_PERMISSIONS.DASHBOARD_VIEW,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-inbox',
                title: 'Inbox',
                description: 'All AI conversations',
                path: PATHS.SETTINGS.WHATSAPP_AI.INBOX,
                icon: Inbox,
                permission: WHATSAPP_AI_PERMISSIONS.VIEW,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-active',
                title: 'Active Conversations',
                description: 'Ongoing AI chats',
                path: PATHS.SETTINGS.WHATSAPP_AI.ACTIVE,
                icon: MessagesSquare,
                permissions: [
                    WHATSAPP_AI_PERMISSIONS.CONVERSATIONS_VIEW_ALL,
                    WHATSAPP_AI_PERMISSIONS.CONVERSATIONS_VIEW_ASSIGNED,
                ],
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-waiting',
                title: 'Waiting for Human',
                description: 'Conversations requiring human response',
                path: PATHS.SETTINGS.WHATSAPP_AI.WAITING_HUMAN,
                icon: UserRound,
                permission: WHATSAPP_AI_PERMISSIONS.TAKEOVER,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-lead-drafts',
                title: 'Lead Drafts',
                description: 'AI-generated lead drafts',
                path: PATHS.SETTINGS.WHATSAPP_AI.LEAD_DRAFTS,
                icon: FileText,
                permissions: [
                    WHATSAPP_AI_PERMISSIONS.LEAD_DRAFT_CREATE,
                    WHATSAPP_AI_PERMISSIONS.LEAD_DRAFT_APPROVE,
                ],
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-reply-drafts',
                title: 'Reply Drafts',
                description: 'AI-generated reply drafts',
                path: PATHS.SETTINGS.WHATSAPP_AI.REPLY_DRAFTS,
                icon: Reply,
                permission: WHATSAPP_AI_PERMISSIONS.DRAFTS_VIEW,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-rules',
                title: 'AI Rules',
                description: 'Automation rules and conditions',
                path: PATHS.SETTINGS.WHATSAPP_AI.RULES,
                icon: SlidersHorizontal,
                permission: WHATSAPP_AI_PERMISSIONS.SETTINGS_MANAGE,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-settings',
                title: 'AI Settings',
                description: 'AI configuration and preferences',
                path: PATHS.SETTINGS.WHATSAPP_AI.SETTINGS,
                icon: Settings,
                permission: WHATSAPP_AI_PERMISSIONS.SETTINGS_MANAGE,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-knowledge',
                title: 'Knowledge',
                description: 'Knowledge base for AI replies',
                path: PATHS.SETTINGS.WHATSAPP_AI.KNOWLEDGE,
                icon: BookOpen,
                permissions: [
                    WHATSAPP_AI_PERMISSIONS.KNOWLEDGE_MANAGE,
                    WHATSAPP_AI_PERMISSIONS.KNOWLEDGE_APPROVE,
                ],
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-documents',
                title: 'Documents',
                description: 'Document library for sharing',
                path: PATHS.SETTINGS.WHATSAPP_AI.DOCUMENTS,
                icon: FileStack,
                permissions: [
                    WHATSAPP_AI_PERMISSIONS.DOCUMENTS_MANAGE,
                    WHATSAPP_AI_PERMISSIONS.DOCUMENTS_SHARE,
                ],
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
            {
                id: 'communication-whatsapp-ai-audit',
                title: 'Audit Logs',
                description: 'AI activity and audit trail',
                path: PATHS.SETTINGS.WHATSAPP_AI.AUDIT,
                icon: ScrollText,
                permission: WHATSAPP_AI_PERMISSIONS.AUDIT_VIEW,
                featurePath: WHATSAPP_AI_FEATURE,
                moduleCode: 'whatsapp_ai',
            },
        ],
    },
    {
        id: 'bulk',
        title: 'Bulk Messaging',
        description: 'Create and manage campaigns, templates, recipients and message history.',
        icon: Megaphone,
        expandedHeading: 'Bulk Messaging Tools',
        featurePath: 'communication.enableWhatsappBulk',
        moduleCode: 'whatsapp_bulk',
        tools: [
            {
                id: 'communication-bulk-campaigns',
                title: 'Campaigns',
                description: 'Create and manage bulk campaigns',
                path: PATHS.SETTINGS.WHATSAPP_BULK.CAMPAIGNS,
                icon: Megaphone,
                permission: 'whatsapp_bulk.campaigns.view',
                featurePath: 'communication.enableWhatsappBulk',
                moduleCode: 'whatsapp_bulk',
            },
            {
                id: 'communication-bulk-matter',
                title: 'Templates / Matter Master',
                description: 'Message matters used in campaigns',
                path: PATHS.SETTINGS.WHATSAPP_BULK.MATTERS,
                icon: FileText,
                permission: 'whatsapp_bulk.matter_master.view',
                featurePath: 'communication.enableWhatsappBulk',
                moduleCode: 'whatsapp_bulk',
            },
            {
                id: 'communication-bulk-history',
                title: 'Campaign History',
                description: 'Past campaign runs and outcomes',
                path: PATHS.SETTINGS.WHATSAPP_BULK.HISTORY,
                icon: History,
                permission: 'whatsapp_bulk.campaigns.view',
                featurePath: 'communication.enableWhatsappBulk',
                moduleCode: 'whatsapp_bulk',
            },
            {
                id: 'communication-bulk-blacklist',
                title: 'Blacklist / Opt-out',
                description: 'Blocked and opted-out numbers',
                path: PATHS.SETTINGS.WHATSAPP_BULK.BLACKLIST,
                icon: Ban,
                permission: 'whatsapp_bulk.blacklist.view',
                featurePath: 'communication.enableWhatsappBulk',
                moduleCode: 'whatsapp_bulk',
            },
            {
                id: 'communication-bulk-number-health',
                title: 'Number Health',
                description: 'Availability and delivery readiness',
                path: PATHS.SETTINGS.WHATSAPP_BULK.NUMBER_HEALTH,
                icon: HeartPulse,
                permission: 'whatsapp_bulk.number_health.view',
                featurePath: 'communication.enableWhatsappBulk',
                moduleCode: 'whatsapp_bulk',
            },
            {
                id: 'communication-bulk-settings',
                title: 'Bulk Settings',
                description: 'Bulk messaging configuration',
                path: PATHS.SETTINGS.WHATSAPP_BULK.SETTINGS,
                icon: Settings,
                permission: 'whatsapp_bulk.settings.view',
                featurePath: 'communication.enableWhatsappBulk',
                moduleCode: 'whatsapp_bulk',
            },
        ],
    },
    {
        id: 'settings',
        title: 'Settings',
        description: 'Manage WhatsApp connection, session status and configuration.',
        icon: Settings,
        expandedHeading: 'WhatsApp Settings',
        tools: [
            {
                id: 'whatsapp',
                title: 'Connection',
                description: 'Session status, linked number and reconnect',
                path: PATHS.SETTINGS.WHATSAPP,
                icon: Settings,
                permission: 'whatsapp.whatsapp_settings.view',
                moduleCode: 'whatsapp',
            },
        ],
    },
];

export default function WhatsAppHomePage() {
    return (
        <ExpandableModuleHome
            title="WhatsApp - Home"
            subtitle="Manage WhatsApp communication, AI assistant, bulk messaging and connection settings."
            sections={SECTIONS}
            sessionKey={SESSION_SECTION_KEY}
            dataComponent="whatsapp-home"
        />
    );
}
