export const ENGINE_VERSION = 'contact-intelligence-v1';

export const DEFAULT_ROLE_SEED = Object.freeze([
    { roleName: 'Owner', roleGroup: 'Leadership', keywords: ['owner', 'proprietor'], seniorityWeight: 95, decisionMakerWeight: 95, applicableOpportunityTypes: ['all'] },
    { roleName: 'Founder', roleGroup: 'Leadership', keywords: ['founder', 'co-founder'], seniorityWeight: 95, decisionMakerWeight: 90, applicableOpportunityTypes: ['all'] },
    { roleName: 'Director', roleGroup: 'Leadership', keywords: ['director', 'board director'], seniorityWeight: 90, decisionMakerWeight: 90, applicableOpportunityTypes: ['all'] },
    { roleName: 'Managing Director', roleGroup: 'Leadership', keywords: ['managing director', 'md'], seniorityWeight: 95, decisionMakerWeight: 95, applicableOpportunityTypes: ['all'] },
    { roleName: 'CEO', roleGroup: 'Leadership', keywords: ['ceo', 'chief executive'], seniorityWeight: 98, decisionMakerWeight: 95, applicableOpportunityTypes: ['all'] },
    { roleName: 'Purchase', roleGroup: 'Procurement', keywords: ['purchase', 'buyer'], seniorityWeight: 70, decisionMakerWeight: 85, applicableOpportunityTypes: ['oem', 'purchase', 'procurement', 'manufacturing'] },
    { roleName: 'Procurement', roleGroup: 'Procurement', keywords: ['procurement', 'sourcing'], seniorityWeight: 75, decisionMakerWeight: 90, applicableOpportunityTypes: ['oem', 'purchase', 'procurement'] },
    { roleName: 'Sourcing', roleGroup: 'Procurement', keywords: ['sourcing'], seniorityWeight: 70, decisionMakerWeight: 80, applicableOpportunityTypes: ['oem', 'purchase', 'procurement'] },
    { roleName: 'Technical', roleGroup: 'Engineering', keywords: ['technical', 'engineer'], seniorityWeight: 70, decisionMakerWeight: 80, applicableOpportunityTypes: ['technical', 'oem', 'r&d', 'engineering'] },
    { roleName: 'R&D', roleGroup: 'Engineering', keywords: ['r&d', 'research', 'development'], seniorityWeight: 75, decisionMakerWeight: 85, applicableOpportunityTypes: ['technical', 'r&d', 'oem'] },
    { roleName: 'Engineering', roleGroup: 'Engineering', keywords: ['engineering'], seniorityWeight: 70, decisionMakerWeight: 75, applicableOpportunityTypes: ['technical', 'engineering', 'oem'] },
    { roleName: 'Sales', roleGroup: 'Commercial', keywords: ['sales', 'business development', 'bd'], seniorityWeight: 65, decisionMakerWeight: 70, applicableOpportunityTypes: ['distributor', 'dealer', 'export', 'sales'] },
    { roleName: 'Export', roleGroup: 'Commercial', keywords: ['export', 'exports'], seniorityWeight: 70, decisionMakerWeight: 80, applicableOpportunityTypes: ['export', 'distributor'] },
    { roleName: 'Marketing', roleGroup: 'Commercial', keywords: ['marketing'], seniorityWeight: 55, decisionMakerWeight: 50, applicableOpportunityTypes: ['sales', 'dealer'] },
    { roleName: 'Dealer', roleGroup: 'Channel', keywords: ['dealer'], seniorityWeight: 60, decisionMakerWeight: 65, applicableOpportunityTypes: ['dealer'] },
    { roleName: 'Distributor', roleGroup: 'Channel', keywords: ['distributor'], seniorityWeight: 65, decisionMakerWeight: 70, applicableOpportunityTypes: ['distributor', 'export'] },
    { roleName: 'Consultant', roleGroup: 'Advisory', keywords: ['consultant', 'architect'], seniorityWeight: 70, decisionMakerWeight: 75, applicableOpportunityTypes: ['consultant', 'projects'] },
    { roleName: 'Projects', roleGroup: 'Delivery', keywords: ['projects', 'project manager'], seniorityWeight: 65, decisionMakerWeight: 70, applicableOpportunityTypes: ['projects', 'system integrator'] },
    { roleName: 'Operations', roleGroup: 'Operations', keywords: ['operations', 'production'], seniorityWeight: 65, decisionMakerWeight: 60, applicableOpportunityTypes: ['oem', 'manufacturing'] },
    { roleName: 'Accounts', roleGroup: 'Finance', keywords: ['accounts', 'finance'], seniorityWeight: 50, decisionMakerWeight: 40, applicableOpportunityTypes: ['all'] },
    { roleName: 'Support', roleGroup: 'Support', keywords: ['support', 'service'], seniorityWeight: 40, decisionMakerWeight: 30, applicableOpportunityTypes: ['all'] },
    { roleName: 'Reception', roleGroup: 'General', keywords: ['reception', 'front desk'], seniorityWeight: 20, decisionMakerWeight: 10, applicableOpportunityTypes: ['all'] },
    { roleName: 'General Contact', roleGroup: 'General', keywords: ['info', 'contact', 'general'], seniorityWeight: 15, decisionMakerWeight: 15, applicableOpportunityTypes: ['all'] },
    { roleName: 'Unknown', roleGroup: 'General', keywords: [], seniorityWeight: 10, decisionMakerWeight: 10, applicableOpportunityTypes: ['all'] },
]);

export const EMAIL_PREFIX_MAP = Object.freeze({
    sales: 'sales',
    purchase: 'purchase',
    procurement: 'procurement',
    sourcing: 'sourcing',
    info: 'info',
    support: 'support',
    accounts: 'accounts',
    export: 'export',
    projects: 'projects',
    director: 'director',
    contact: 'info',
    hello: 'info',
    admin: 'unknown',
});
