import { PATHS } from '../routes/paths';

export const ROLES = {
    SUPERADMIN: 'superadmin',
    ADMIN: 'admin',
    MANAGER: 'manager',
    STAFF: 'staff',
    VIEWER: 'viewer',
};

export const menuConfig = [

    {
        id: 'customers',
        title: 'Customers',
        icon: 'PeopleIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
        children: [
            {
                id: 'customer-list',
                title: 'Customer Master',
                path: PATHS.CUSTOMERS.LIST,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
                permission: 'view_customers',
            },
            {
                id: 'reminder-tasks',
                title: 'Reminder Tasks',
                path: '/reminders',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_reminders',
            },
            {
                id: 'follow-up-tracker',
                title: 'Follow-up Dashboard',
                path: '/followups',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
        ],
    },

    {
        id: 'tasks',
        title: 'Task Management',
        icon: 'AssignmentIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'view_tasks',
        children: [
            {
                id: 'task-create',
                title: 'Create Task',
                path: '/tasks/create',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'add_task',
            },
            {
                id: 'task-list',
                title: 'Manage Tasks',
                path: '/tasks/list',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_tasks',
            },
            {
                id: 'task-groups',
                title: 'Task Groups',
                path: PATHS.TASKS.GROUPS,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_groups',
            },
        ],
    },
    {
        id: 'reports',
        title: 'Reports',
        icon: 'BarChartIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER],
        permission: 'view_reports',
        children: [
            {
                id: 'report-customer-master',
                title: 'Customer Master',
                path: PATHS.REPORTS.CUSTOMER_MASTER,
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'view_reports',
            },
            {
                id: 'report-followup-tracker',
                title: 'Follow-up Tracker Report',
                path: '/reports/followups',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'view_reports',
            },
            {
                id: 'report-open-reminders',
                title: 'Open Reminders',
                path: '/reports/open-reminders',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
                // Open Reminders should just require general view reminders permission
                permission: 'view_reminders',
            },
            {
                id: 'report-dashboard-followup',
                title: 'Follow-up Dashboard',
                path: '/reports/followup-dashboard',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'view_reports',
            },
            {
                id: 'report-followup-task',
                title: 'Follow-up Task Report',
                path: '/reports/followup-task-report',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'view_reports',
            },
            {
                id: 'report-task-reminders',
                title: 'Task Reminder Report',
                path: '/reports/task-reminders',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_reports',
            },
        ],
    },
    {
        id: 'inventory',
        title: 'Inventory',
        icon: 'InventoryIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'view_inventory',
        children: [
            {
                id: 'item-master',
                title: 'Item Master',
                path: '/inventory/items',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_inventory',
            },
            {
                id: 'item-type-master',
                title: 'Item Types',
                path: '/inventory/item-types',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'view_inventory',
            },
            {
                id: 'item-group-master',
                title: 'Item Groups',
                path: '/inventory/item-groups',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'view_inventory',
            },
            {
                id: 'bom-master',
                title: 'Bill of Materials (BOM)',
                path: PATHS.INVENTORY.BOM.ROOT,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_inventory',
            },
            {
                id: 'raw-material-report',
                title: 'Raw Material Stock Report',
                path: '/inventory/stock/raw-material',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_inventory',
            },
            {
                id: 'finished-goods-report',
                title: 'Finished Goods Stock Report',
                path: '/inventory/stock/finished-goods',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_inventory',
            },
            {
                id: 'stock-ledger',
                title: 'Stock Movement Ledger',
                path: '/inventory/stock/ledger',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_inventory',
            },
        ],
    },
    {
        id: 'production',
        title: 'Production',
        icon: 'FactoryIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'view_production',
        children: [
            {
                id: 'prod-dashboard',
                title: 'Dashboard',
                path: PATHS.PRODUCTION.DASHBOARD,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_production',
            },
            {
                id: 'prod-output',
                title: 'Production Output Entry',
                path: '/production/outputs/new',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_production',
            },
            {
                id: 'comp-replacement',
                title: 'Component Replacement',
                path: '/production/component-replacements/new',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_production',
            },
            {
                id: 'prod-rejection',
                title: 'Production Rejection',
                path: '/production/rejections/new',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_production',
            },
            {
                id: 'prod-rework',
                title: 'Failure & Rework',
                path: PATHS.PRODUCTION.REWORK.DASHBOARD,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'view_production',
            },
        ],
    },
    {
        id: 'purchase',
        title: 'Purchase',
        icon: 'ShoppingCartIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        children: [
            {
                id: 'suppliers',
                title: 'Suppliers',
                path: PATHS.PURCHASE.SUPPLIERS,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'purchase-orders',
                title: 'Purchase Orders',
                path: PATHS.PURCHASE.ORDERS,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'grn',
                title: 'Goods Receipt (GRN)',
                path: PATHS.PURCHASE.GRN,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'purchase-invoices',
                title: 'Purchase Invoices',
                path: PATHS.PURCHASE.INVOICES,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
        ],
    },
    {
        id: 'sales',
        title: 'Sales',
        icon: 'ShoppingBagIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        children: [
            {
                id: 'sales-orders',
                title: 'Sales Orders',
                path: PATHS.SALES.ORDERS,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'sales-invoices',
                title: 'Tax Invoices (GST)',
                path: PATHS.SALES.INVOICES,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'invoice-series',
                title: 'Invoice Series',
                path: PATHS.SALES.INVOICE_SERIES,
                roles: [ROLES.ADMIN],
            },
        ],
    },
    {
        id: 'service',
        title: 'Service',
        icon: 'SettingsIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        children: [
            {
                id: 'complaints',
                title: 'Customer Complaints',
                path: PATHS.SERVICE.COMPLAINTS,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'replacement-dashboard',
                title: 'Replacement Dashboard',
                path: PATHS.SERVICE.REPLACEMENT_DASHBOARD,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
            {
                id: 'replacement-dispatches',
                title: 'Replacement Dispatches',
                path: '/service/replacement-dispatches/new',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
            },
        ],
    },
    {
        id: 'accounts',
        title: 'Accounts',
        icon: 'AccountBalanceWalletIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        children: [
            { id: 'receipt-entry', title: 'Receipt Entry', path: PATHS.ACCOUNTS.RECEIPT_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'payment-entry', title: 'Payment Entry', path: PATHS.ACCOUNTS.PAYMENT_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'expense-entry', title: 'Expense Voucher', path: PATHS.ACCOUNTS.EXPENSE_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'journal-entry', title: 'Journal Voucher', path: PATHS.ACCOUNTS.JOURNAL_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'vouchers', title: 'Voucher Register', path: PATHS.ACCOUNTS.VOUCHER_LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'group-master', title: 'Account Groups', path: PATHS.ACCOUNTS.GROUP_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'ledger-master', title: 'Ledger Master', path: PATHS.ACCOUNTS.LEDGER_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'cash-bank', title: 'Cash / Bank Master', path: PATHS.ACCOUNTS.CASH_BANK_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'voucher-types', title: 'Voucher Types', path: PATHS.ACCOUNTS.VOUCHER_TYPE_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'ledger-report', title: 'Ledger Report', path: PATHS.ACCOUNTS.LEDGER_REPORT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER] },
            { id: 'sales-register', title: 'Sales Register', path: PATHS.ACCOUNTS.SALES_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'purchase-register', title: 'Purchase Register', path: PATHS.ACCOUNTS.PURCHASE_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'day-book', title: 'Day Book', path: PATHS.ACCOUNTS.DAY_BOOK, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'cash-book', title: 'Cash Book', path: PATHS.ACCOUNTS.CASH_BOOK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER] },
            { id: 'bank-book', title: 'Bank Book', path: PATHS.ACCOUNTS.BANK_BOOK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER] },
            { id: 'outstanding', title: 'Outstanding Report', path: PATHS.ACCOUNTS.OUTSTANDING_REPORT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER] },
            { id: 'fixed-assets-master', title: 'Fixed Asset Master', path: PATHS.ACCOUNTS.FIXED_ASSETS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF] },
            { id: 'asset-category-master', title: 'Asset Category Master', path: PATHS.ACCOUNTS.ASSET_CATEGORIES, roles: [ROLES.ADMIN, ROLES.MANAGER] },
            { id: 'asset-location-master', title: 'Asset Location Master', path: PATHS.ACCOUNTS.ASSET_LOCATIONS, roles: [ROLES.ADMIN, ROLES.MANAGER] },
        ]
    },
    {
        id: 'admin',
        title: 'Admin',
        icon: 'SettingsIcon',
        roles: [ROLES.ADMIN], // Admin only
        children: [
            {
                id: 'company-profile',
                title: 'Company Profile',
                path: PATHS.SETTINGS.COMPANY_PROFILE,
                roles: [ROLES.ADMIN],
            },
            {
                id: 'whatsapp-settings',
                title: 'WhatsApp Settings',
                path: PATHS.SETTINGS.WHATSAPP,
                roles: [ROLES.ADMIN],
                icon: 'WhatsAppIcon',
            },
            {
                id: 'user-management',
                title: 'User Management',
                path: '/admin/users',
                roles: [ROLES.ADMIN],
            },
        ],
    },
];

