import { PATHS } from '../routes/paths';

export const ROLES = {
    SUPERADMIN: 'superadmin',
    ADMIN: 'admin',
    MANAGER: 'manager',
    STAFF: 'staff',
    VIEWER: 'viewer',
};

export const menuConfig = [
    {
        id: 'dashboard',
        title: 'Home',
        icon: 'BusinessIcon',
        path: '/',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
        permission: null
    },
    {
        id: 'crm',
        title: 'CRM',
        icon: 'BusinessIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
        permission: 'customers',
        children: [
            {
                id: 'crm-customers',
                title: 'Customers',
                icon: 'PeopleIcon',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
                permission: 'customers',
                children: [
                    {
                        id: 'customer-list',
                        title: 'Customer Master',
                        path: PATHS.CUSTOMERS.LIST,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
                        permission: 'customers.customer_master.view',
                    },
                    {
                        id: 'reminder-tasks',
                        title: 'Reminder Tasks',
                        path: '/reminders',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'customers.reminder_tasks.view',
                    },
                    {
                        id: 'follow-up-tracker',
                        title: 'Follow-up Dashboard',
                        path: '/followups',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'customers.follow_up.view',
                    },
                    {
                        id: 'distributor-master',
                        title: 'Distributor Master',
                        path: '/distributors',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'sales.sales_invoices.view',
                    },
                ]
            },
            {
                id: 'crm-leads',
                title: 'WhatsApp Leads',
                icon: 'ChatIcon',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'crm.leads.view',
                children: [
                    {
                        id: 'lead-list',
                        title: 'Leads / Inquiries',
                        path: '/crm/leads',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'crm.leads.view',
                    },
                    {
                        id: 'lead-create-whatsapp',
                        title: 'Convert WhatsApp Chat → Lead',
                        path: '/crm/leads',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'crm.leads.convert_whatsapp',
                    },
                ]
            },
            {
                id: 'crm-product-catalog',
                title: 'Product Catalog',
                icon: 'PackageIcon',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'crm.product_catalog.view',
                children: [
                    {
                        id: 'product-catalog-list',
                        title: 'Catalog Master',
                        path: '/crm/product-catalog',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'crm.product_catalog.view',
                    },
                    {
                        id: 'product-catalog-share',
                        title: 'Share Catalog / Datasheet',
                        path: '/crm/product-catalog',
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'crm.product_catalog.share',
                    },
                ]
            },
            {
                id: 'data-extractor',
                title: 'Data Extractor',
                icon: 'SearchIcon',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'data_extractor.extractor.view',
                children: [
                    {
                        id: 'data-extractor-keyword',
                        title: 'Keyword Search',
                        path: PATHS.DATA_EXTRACTOR.KEYWORD_SEARCH,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'data_extractor.extractor.search',
                    },
                    {
                        id: 'data-extractor-home',
                        title: 'Market Finder',
                        path: PATHS.DATA_EXTRACTOR.KEYWORD_SEARCH,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'data_extractor.extractor.view',
                    },
                    {
                        id: 'data-extractor-manual',
                        title: 'Manual URL Extract',
                        path: PATHS.DATA_EXTRACTOR.MANUAL_URL,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'data_extractor.extractor.search',
                    },
                    {
                        id: 'data-extractor-import',
                        title: 'Excel / CSV Import',
                        path: PATHS.DATA_EXTRACTOR.IMPORT,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'data_extractor.extractor.import',
                    },
                    {
                        id: 'data-extractor-history',
                        title: 'Search History',
                        path: PATHS.DATA_EXTRACTOR.HISTORY,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'data_extractor.extractor.view',
                    },
                    {
                        id: 'data-extractor-leads',
                        title: 'Extracted Leads',
                        path: PATHS.DATA_EXTRACTOR.LEADS,
                        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                        permission: 'data_extractor.extractor.view',
                    },
                    {
                        id: 'data-extractor-settings',
                        title: 'Extractor Settings',
                        path: PATHS.DATA_EXTRACTOR.SETTINGS,
                        roles: [ROLES.ADMIN],
                        permission: 'data_extractor.extractor.settings',
                    },
                ],
            },
            {
                id: 'crm-kanban',
                title: 'Kanban / Workflow',
                icon: 'BarChartIcon',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'customers',
                children: [
                    { id: 'crm-kanban-sales-inquiry', title: 'Sales Inquiry', path: '/crm/kanban/sales-inquiry', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'customers' },
                    { id: 'crm-kanban-task', title: 'Tasks', path: '/crm/kanban/tasks', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tasks' },
                    { id: 'crm-kanban-purchase-rfq', title: 'Purchase RFQ', path: '/crm/kanban/purchase-rfq', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase' },
                    { id: 'crm-kanban-production', title: 'Production', path: '/crm/kanban/production', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production' },
                    { id: 'crm-kanban-dispatch', title: 'Dispatch', path: '/crm/kanban/dispatch', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'sales' },
                    { id: 'crm-kanban-gst-tds', title: 'GST / TDS', path: '/crm/kanban/gst-tds', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst' },
                    { id: 'crm-kanban-complaint', title: 'Complaints', path: '/crm/kanban/complaints', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'service' },
                    { id: 'crm-kanban-apk', title: 'APK View', path: '/crm/kanban/apk', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'customers' },
                ],
            },
            {
                id: 'crm-reports',
                title: 'Reports',
                icon: 'BarChartIcon',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
                permission: 'reports',
                children: [
                    { id: 'report-customer-master', title: 'Customer Master Report', path: PATHS.REPORTS.CUSTOMER_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.customer_master_report.view' },
                    { id: 'report-customer-kyc', title: 'Customer KYC / Documents', path: PATHS.REPORTS.CUSTOMER_KYC, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.customer_kyc_reports.view' },
                    { id: 'report-supplier-kyc', title: 'Supplier KYC / Documents', path: PATHS.REPORTS.SUPPLIER_KYC, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.supplier_kyc_reports.view' },
                    { id: 'report-sales-marketing', title: 'Sales & Marketing MIS', path: '/mis/sales-marketing', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'mis.sales_marketing.view' },
                    { id: 'report-sales-conversion', title: 'Sales Conversion Analysis', path: '/mis/sales-conversion', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'mis.sales_conversion.view' },
                    { id: 'report-leads', title: 'Lead Report', path: '/reports/leads', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'reports.lead_report.view' },
                    { id: 'report-followup-tracker', title: 'Follow-up Tracker Report', path: '/reports/followups', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.followup_report.view' },
                    { id: 'report-followup-dashboard', title: 'Follow-up Dashboard Report', path: '/reports/followup-dashboard', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.followup_dashboard_report.view' },
                    { id: 'report-followup-task', title: 'Follow-up Task Report', path: '/reports/followup-task-report', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.followup_task_report.view' },
                    { id: 'report-conversation-history', title: 'Conversation History', path: '/reports/conversation-history', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.conversation_history_report.view' },
                    { id: 'report-task-reminders', title: 'Task Reminder Report', path: '/reports/task-reminders', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'reports.task_reminder_report.view' },
                    { id: 'report-open-reminders', title: 'Open Reminders', path: '/reports/open-reminders', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER], permission: 'reports.reminder_report.view' },
                    { id: 'report-incentive', title: 'Sales Incentive Report', path: '/reports/incentive', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports' },
                ]
            }
        ]
    },
    {
        id: 'tasks',
        title: 'Task Management',
        path: '/tasks/home',
        icon: 'AssignmentIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'tasks',
        children: [
            {
                id: 'task-list',
                title: 'Task Hub',
                path: '/tasks/list',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'tasks.task_list.view',
            },
            {
                id: 'task-groups',
                title: 'Task Groups',
                path: PATHS.TASKS.GROUPS,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'tasks.task_groups.view',
            },
        ],
    },
    {
        id: 'messenger',
        title: 'Messenger',
        icon: '💬',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
        path: PATHS.MESSENGER.ROOT,
        permission: 'messenger',
    },
    {
        id: 'whatsapp-root',
        title: 'WhatsApp',
        icon: 'ChatIcon',
        path: PATHS.SETTINGS.WHATSAPP_HOME,
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: null,
        children: [
            {
                id: 'whatsapp-communication-group',
                title: 'WhatsApp Communication',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: null,
                children: [
                    { id: 'whatsapp-chat', title: 'Chats / Conversations', path: '/whatsapp/chat', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp.whatsapp_settings.view' },
                    { id: 'communication-bulk-campaigns', title: 'WhatsApp Bulk Message Utility', path: PATHS.SETTINGS.WHATSAPP_BULK.CAMPAIGNS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_bulk.campaigns.view' },
                    { id: 'communication-bulk-matter', title: 'WhatsApp Matter Master', path: PATHS.SETTINGS.WHATSAPP_BULK.MATTERS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_bulk.matter_master.view' },
                    { id: 'communication-bulk-blacklist', title: 'WhatsApp Blacklist', path: PATHS.SETTINGS.WHATSAPP_BULK.BLACKLIST, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_bulk.blacklist.view' },
                    { id: 'communication-bulk-history', title: 'Campaign History', path: PATHS.SETTINGS.WHATSAPP_BULK.HISTORY, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_bulk.campaigns.view' },
                    { id: 'communication-bulk-number-health', title: 'Number Health', path: PATHS.SETTINGS.WHATSAPP_BULK.NUMBER_HEALTH, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_bulk.number_health.view' },
                    { id: 'communication-bulk-settings', title: 'WhatsApp Bulk Messaging Settings', path: PATHS.SETTINGS.WHATSAPP_BULK.SETTINGS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_bulk.settings.view' },
                ],
            },
            {
                id: 'communication-whatsapp-ai-group',
                title: 'WhatsApp AI',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: null,
                children: [
                    { id: 'communication-whatsapp-ai-dashboard', title: 'Dashboard', path: PATHS.SETTINGS.WHATSAPP_AI.DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.dashboard.view' },
                    { id: 'communication-whatsapp-ai-inbox', title: 'Inbox', path: PATHS.SETTINGS.WHATSAPP_AI.INBOX, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.module.view' },
                    { id: 'communication-whatsapp-ai-active', title: 'Active Conversations', path: PATHS.SETTINGS.WHATSAPP_AI.ACTIVE, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.conversations.view_assigned' },
                    { id: 'communication-whatsapp-ai-waiting', title: 'Waiting for Human', path: PATHS.SETTINGS.WHATSAPP_AI.WAITING_HUMAN, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.module.takeover' },
                    { id: 'communication-whatsapp-ai-lead-drafts', title: 'Lead Drafts', path: PATHS.SETTINGS.WHATSAPP_AI.LEAD_DRAFTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.lead_draft.create' },
                    { id: 'communication-whatsapp-ai-reply-drafts', title: 'Reply Drafts', path: PATHS.SETTINGS.WHATSAPP_AI.REPLY_DRAFTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.drafts.view' },
                    { id: 'communication-whatsapp-ai-knowledge', title: 'Knowledge', path: PATHS.SETTINGS.WHATSAPP_AI.KNOWLEDGE, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.knowledge.manage' },
                    { id: 'communication-whatsapp-ai-documents', title: 'Documents', path: PATHS.SETTINGS.WHATSAPP_AI.DOCUMENTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'whatsapp_ai.documents.manage' },
                    { id: 'communication-whatsapp-ai-rules', title: 'Rules', path: PATHS.SETTINGS.WHATSAPP_AI.RULES, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_ai.settings.manage' },
                    { id: 'communication-whatsapp-ai-settings', title: 'AI Settings', path: PATHS.SETTINGS.WHATSAPP_AI.SETTINGS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_ai.settings.manage' },
                    { id: 'communication-whatsapp-ai-audit', title: 'Audit Logs', path: PATHS.SETTINGS.WHATSAPP_AI.AUDIT, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'whatsapp_ai.audit.view' },
                ],
            },
            {
                id: 'whatsapp',
                title: 'WhatsApp Settings',
                path: PATHS.SETTINGS.WHATSAPP,
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'whatsapp.whatsapp_settings.view',
            },
        ],
    },
    {
        id: 'sales',
        title: 'Sales',
        icon: 'ShoppingBagIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'sales',
        children: [
            { id: 'sales-orders', title: 'Sales Orders', path: PATHS.SALES.ORDERS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'sales.sales_orders.view' },
            { id: 'sales-invoices', title: 'Tax Invoices (GST)', path: PATHS.SALES.INVOICES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'sales.sales_invoices.view' },
            { id: 'eway-bills', title: 'E-Way Bill Tracking', path: PATHS.EWAY_BILL.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'sales.sales_invoices.view' },
            { id: 'e-invoices', title: 'E-Invoice / IRN Tracking', path: PATHS.E_INVOICE.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'sales.sales_invoices.view' },
            { id: 'logistics-master', title: 'Logistics & Courier Master', path: PATHS.TRANSPORTERS.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'sales.sales_invoices.view' },
            { id: 'invoice-series', title: 'Invoice Series', path: PATHS.SALES.INVOICE_SERIES, roles: [ROLES.ADMIN], permission: 'sales.invoice_series.view' },
            { id: 'bulk-renumber', title: 'Bulk Renumbering', path: PATHS.SALES.BULK_RENUMBER, roles: [ROLES.ADMIN], permission: 'sales.sales_invoices.view' },
        ],
    },
    {
        id: 'purchase',
        title: 'Purchase',
        icon: 'ShoppingCartIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'purchase',
        children: [
            { id: 'suppliers', title: 'Suppliers', path: PATHS.PURCHASE.SUPPLIERS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.suppliers.view' },
            { id: 'purchase-rfq', title: 'Purchase RFQ', path: PATHS.PURCHASE.RFQ, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.purchase_rfq.view' },
            { id: 'supplier-quotations', title: 'Supplier Quotations', path: PATHS.PURCHASE.SUPPLIER_QUOTATIONS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.supplier_quotation.view' },
            { id: 'quotation-comparison', title: 'Quotation Comparison', path: PATHS.PURCHASE.QUOTATION_COMPARISON_LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.quotation_comparison.view' },
            { id: 'purchase-rfq-reports', title: 'RFQ Reports', path: PATHS.PURCHASE.RFQ_REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.purchase_rfq.view' },
            { id: 'purchase-orders', title: 'Purchase Orders', path: PATHS.PURCHASE.ORDERS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.purchase_orders.view' },
            { id: 'grn', title: 'Goods Receipt (GRN)', path: PATHS.PURCHASE.GRN, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.grn.view' },
            { id: 'purchase-invoices', title: 'Purchase Invoices', path: PATHS.PURCHASE.INVOICES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.purchase_invoices.view' },
            { id: 'consumable-cost-report', title: 'Consumable Cost Analysis', path: '/reports/consumable-cost', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'purchase.purchase_invoices.view' },
        ],
    },
    {
        id: 'documents-menu',
        title: 'Documents',
        icon: 'DocumentIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'documents',
        children: [
            { id: 'scan-bills', title: 'Scan Bills', path: PATHS.DOCUMENTS.SCAN_BILLS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'documents.scan_bills.view' },
            { id: 'missing-attachments', title: 'Missing Attachments', path: PATHS.DOCUMENTS.MISSING, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'documents.missing_attachments.view' },
            {
                id: 'smart-import-hub',
                title: 'AI Smart Import',
                path: PATHS.DOCUMENTS.SMART_IMPORT_HUB,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'scan_entry.scan_entry.view',
            },
            {
                id: 'scan-entry-group',
                title: 'Scan Entry (OCR)',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'scan_entry.scan_entry.view',
                children: [
                    { id: 'scan-entry-drafts', title: 'Pending OCR Drafts', path: PATHS.DOCUMENTS.SCAN_ENTRY_DRAFTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'scan_entry.scan_entry.view' },
                    { id: 'scan-entry-bulk', title: 'Bulk Import', path: PATHS.DOCUMENTS.SCAN_ENTRY_BULK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'scan_entry.scan_entry.upload' },
                    { id: 'scan-entry-reports', title: 'Scan Entry Reports', path: PATHS.DOCUMENTS.SCAN_ENTRY_REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'scan_entry.scan_entry.view' },
                    { id: 'scan-entry-keywords', title: 'Expense Keyword Map', path: PATHS.DOCUMENTS.SCAN_ENTRY_KEYWORDS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'scan_entry.scan_entry.review' },
                ],
            },
        ],
    },
    {
        id: 'inventory',
        title: 'Inventory',
        icon: 'InventoryIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'inventory',
        children: [
            {
                id: 'item-master',
                title: 'Item Master',
                path: '/inventory/items',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'inventory.item_master.view',
            },
            {
                id: 'item-type-master',
                title: 'Item Types',
                path: '/inventory/item-types',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'inventory.item_types.view',
            },
            {
                id: 'item-group-master',
                title: 'Item Groups',
                path: '/inventory/item-groups',
                roles: [ROLES.ADMIN, ROLES.MANAGER],
                permission: 'inventory.item_groups.view',
            },
            {
                id: 'bom-master',
                title: 'Bill of Materials (BOM)',
                path: PATHS.INVENTORY.BOM.ROOT,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'inventory.bom.view',
            },
            {
                id: 'raw-material-report',
                title: 'Raw Material Stock Report',
                path: '/inventory/stock/raw-material',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'inventory.raw_material_report.view',
            },
            {
                id: 'finished-goods-report',
                title: 'Finished Goods Stock Report',
                path: '/inventory/stock/finished-goods',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'inventory.finished_goods_report.view',
            },
            {
                id: 'stock-ledger',
                title: 'Stock Movement Ledger',
                path: '/inventory/stock/ledger',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'inventory.stock_ledger.view',
            },
        ],
    },
    {
        id: 'production',
        title: 'Production',
        icon: 'FactoryIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'production',
        children: [
            { id: 'prod-dashboard', title: 'Dashboard', path: PATHS.PRODUCTION.DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.prod_dashboard.view' },
            { id: 'model-conversion', title: 'Model Conversion / Rework', path: '/production/conversion/new', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.prod_output.add', electronicsOnly: true },
            { id: 'comp-replacement', title: 'Component Replacement', path: '/production/component-replacements/new', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.comp_replacement.add', electronicsOnly: true },
            { id: 'prod-rejection', title: 'Production Rejection', path: '/production/rejections/new', roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.prod_rejection.add', electronicsOnly: true },
            { id: 'prod-planning', title: 'Production Planning / MRP', path: PATHS.PRODUCTION.PLANNING.ROOT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.production_planning.view', electronicsOnly: true },
            { id: 'workflow-production', title: 'Workflow Production', path: PATHS.PRODUCTION.WORKFLOW_LOTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.workflow_production.view', electronicsOnly: true },
            { id: 'textile-production', title: 'Textile Production', path: PATHS.PRODUCTION.TEXTILE_LOTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_production.view', textileOnly: true },
            {
                id: 'textile-job-work',
                title: 'Textile Job Work',
                path: PATHS.PRODUCTION.TEXTILE_JOB_WORK.ROOT,
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'production.textile_dyeing_challan.view',
                textileOnly: true,
                children: [
                    { id: 'textile-jw-issue', title: 'Issue Challan', path: PATHS.PRODUCTION.TEXTILE_JOB_WORK.ISSUE, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_dyeing_challan.add', textileOnly: true },
                    { id: 'textile-jw-return', title: 'Return Entry', path: PATHS.PRODUCTION.TEXTILE_JOB_WORK.RETURN, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_dyeing_challan.edit', textileOnly: true },
                    { id: 'textile-jw-stock', title: 'Stock With Job Worker', path: PATHS.PRODUCTION.TEXTILE_JOB_WORK.STOCK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_dyeing_challan.view', textileOnly: true },
                    { id: 'textile-jw-reports', title: 'Job Work Reports', path: PATHS.PRODUCTION.TEXTILE_JOB_WORK.REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_dyeing_challan.view', textileOnly: true },
                ],
            },
            { id: 'textile-job-work-rates', title: 'Job Work Rate Master', path: PATHS.PRODUCTION.TEXTILE_JOB_WORK_RATES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_job_work_rates.view', textileOnly: true },
            { id: 'textile-job-work-reports', title: 'Process Cost Reports', path: PATHS.PRODUCTION.TEXTILE_JOB_WORK_REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_job_work_rates.view', textileOnly: true },
            { id: 'textile-conversion-master', title: 'Conversion Master', path: PATHS.PRODUCTION.TEXTILE_CONVERSION_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_conversion.view', textileOnly: true },
            { id: 'textile-transformation-entry', title: 'Transformation Entry', path: PATHS.PRODUCTION.TEXTILE_TRANSFORMATION_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_conversion.add', textileOnly: true },
            { id: 'textile-transformation-history', title: 'Transformation History', path: PATHS.PRODUCTION.TEXTILE_TRANSFORMATION_HISTORY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_conversion.view', textileOnly: true },
            { id: 'textile-production-workflow', title: 'Textile Production Workflow', path: PATHS.PRODUCTION.TEXTILE_PRODUCTION_WORKFLOW, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_production_workflow.view', textileOnly: true },
            { id: 'textile-production-order', title: 'Textile Production Order', path: PATHS.PRODUCTION.TEXTILE_PRODUCTION_ORDER_NEW, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_production_workflow.add', textileOnly: true },
            { id: 'textile-process-routes', title: 'Process Route Master', path: PATHS.PRODUCTION.TEXTILE_PROCESS_ROUTES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'production.textile_process_route.view', textileOnly: true },
        ],
    },
    {
        id: 'voucher-entry',
        title: 'Voucher Entry',
        icon: 'VoucherIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'accounts',
        children: [
            { id: 'receipt-entry', title: 'Receipt Entry', path: PATHS.ACCOUNTS.RECEIPT_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.receipt_entry.view' },
            { id: 'payment-entry', title: 'Payment Entry', path: PATHS.ACCOUNTS.PAYMENT_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.payment_entry.view' },
            { id: 'contra-entry', title: 'Contra Entry', path: PATHS.ACCOUNTS.CONTRA_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.vouchers.view' },
            { id: 'expense-entry', title: 'Expense Voucher', path: PATHS.ACCOUNTS.EXPENSE_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.expense_entry.view' },
            { id: 'journal-entry', title: 'Journal Voucher', path: PATHS.ACCOUNTS.JOURNAL_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.journal_entry.view' },
            { id: 'credit-notes', title: 'Credit Notes', path: PATHS.ACCOUNTS.CREDIT_NOTES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.credit_notes.view' },
            { id: 'debit-notes', title: 'Debit Notes', path: PATHS.ACCOUNTS.DEBIT_NOTES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.debit_notes.view' },
            { id: 'bill-wise-adjustment', title: 'Bill-wise Adjustment', path: PATHS.ACCOUNTS.BILL_WISE_ADJUSTMENT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.vouchers.view' },
            { id: 'bank-reconciliation', title: 'Bank Reconciliation', path: PATHS.ACCOUNTS.BANK_RECONCILIATION, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.vouchers.view' },
            { id: 'pdc-register', title: 'PDC Register', path: PATHS.PDC.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.vouchers.view' },
            { id: 'narration-templates', title: 'Narration Templates', path: PATHS.NARRATION_TEMPLATES, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
        ]
    },
    {
        id: 'account-master-parent',
        title: 'Account Master',
        icon: 'SettingsIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'accounts',
        children: [
            { id: 'group-master', title: 'Group Master', path: PATHS.ACCOUNT_MASTER.GROUP_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.group_master.view' },
            { id: 'ledger-master', title: 'Ledger Master', path: PATHS.ACCOUNT_MASTER.LEDGER_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.ledger_master.view' },
            { id: 'financial-year-master', title: 'Financial Year Master', path: PATHS.ACCOUNT_MASTER.FINANCIAL_YEAR, roles: [ROLES.ADMIN], permission: 'accounts.financial_year.view' },
            { id: 'voucher-type-master', title: 'Series Master', path: PATHS.ACCOUNT_MASTER.SERIES_MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'cost-centers', title: 'Cost / Profit Centres', path: PATHS.COST_CENTERS.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'budgets', title: 'Budget Master', path: PATHS.BUDGETS.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
        ]
    },
    {
        id: 'accounts',
        title: 'Accounts',
        icon: 'AccountBalanceWalletIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'accounts',
        children: [
            { id: 'vouchers', title: 'Voucher Register', path: PATHS.ACCOUNTS.VOUCHER_LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.vouchers.view' },
            { id: 'ledger-report', title: 'Ledger Report', path: PATHS.ACCOUNTS.LEDGER_REPORT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER], permission: 'accounts.ledger_report.view' },
            { id: 'sales-register', title: 'Sales Register', path: PATHS.ACCOUNTS.SALES_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.sales_register.view' },
            { id: 'purchase-register', title: 'Purchase Register', path: PATHS.ACCOUNTS.PURCHASE_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.purchase_register.view' },
            { id: 'expense-register', title: 'Expense Register', path: PATHS.ACCOUNTS.EXPENSE_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.vouchers.view' },
            { id: 'day-book', title: 'Day Book', path: PATHS.ACCOUNTS.DAY_BOOK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.day_book.view' },
            { id: 'cash-book', title: 'Cash Book', path: PATHS.ACCOUNTS.CASH_BOOK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.cash_book.view' },
            { id: 'bank-book', title: 'Bank Book', path: PATHS.ACCOUNTS.BANK_BOOK, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.bank_book.view' },
            { id: 'outstanding', title: 'Outstanding Report', path: PATHS.ACCOUNTS.OUTSTANDING_REPORT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER], permission: 'accounts.outstanding.view' },
            { id: 'trial-balance-acc', title: 'Trial Balance', path: '/mis/reports/trial-balance', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'mis.trial_balance.view' },
            { id: 'profit-loss-acc', title: 'Profit & Loss', path: '/mis/reports/profit-loss', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'mis.profit_loss.view' },
            { id: 'balance-sheet-acc', title: 'Balance Sheet', path: '/mis/reports/balance-sheet', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'mis.balance_sheet.view' },
            { id: 'interest-payable-statement', title: 'Interest Payable Statement', path: PATHS.ACCOUNTS.INTEREST_PAYABLE, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.interest_payable_statement.view' },
            { id: 'cash-flow', title: 'Cash Flow Statement', path: PATHS.CASH_FLOW, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'comparative-pl', title: 'Comparative P&L', path: PATHS.COMPARATIVE_PL, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'comparative-bs', title: 'Comparative Balance Sheet', path: PATHS.COMPARATIVE_BS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'ageing-analysis', title: 'Ageing Analysis', path: PATHS.AGEING, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'msme-report', title: 'MSME Compliance Report', path: PATHS.MSME_REPORT, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'ratio-analysis', title: 'Ratio Analysis', path: PATHS.RATIO_ANALYSIS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'fund-flow', title: 'Fund Flow Statement', path: PATHS.FUND_FLOW, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'cost-center-pl', title: 'Cost Centre P&L', path: PATHS.COST_CENTERS.PL_REPORT, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'accounting-audit', title: 'Accounting Audit Trail', path: PATHS.ACCOUNTS.ACCOUNTING_AUDIT, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.vouchers.view' },
            { id: 'period-lock', title: 'Period Lock Settings', path: PATHS.ACCOUNTS.PERIOD_LOCK, roles: [ROLES.ADMIN], permission: 'accounts.vouchers.view' },
            { id: 'credit-note-ledger-config', title: 'Credit Note Ledger Config', path: PATHS.ACCOUNTS.CREDIT_NOTE_LEDGER_CONFIG, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.ledger_master.edit' },
            {
                id: 'petty-cash-group',
                title: 'Petty Cash',
                roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
                permission: 'voucher_entry.petty_cash.view',
                children: [
                    { id: 'petty-cash-entry', title: 'Petty Cash Entry', path: PATHS.ACCOUNTS.PETTY_CASH_ENTRY, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'voucher_entry.petty_cash.view' },
                    { id: 'petty-cash-import', title: 'Petty Cash Import', path: PATHS.ACCOUNTS.PETTY_CASH_IMPORT, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'voucher_entry.petty_cash.import' },
                    { id: 'petty-cash-reports', title: 'Petty Cash Reports', path: PATHS.ACCOUNTS.PETTY_CASH_REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'voucher_entry.petty_cash.view' },
                    { id: 'petty-cash-settings', title: 'Petty Cash Settings', path: PATHS.ACCOUNTS.PETTY_CASH_SETTINGS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'voucher_entry.petty_cash.edit' },
                ],
            },
        ]
    },
    {
        id: 'tds',
        title: 'TDS',
        icon: 'ReceiptLongIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'tds',
        children: [
            { id: 'tds-dashboard', title: 'TDS Dashboard', path: PATHS.TDS.DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.dashboard.view' },
            { id: 'tds-master', title: 'TDS Master / Section Rates', path: PATHS.TDS.MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.master.view' },
            { id: 'tds-ledger-mapping', title: 'TDS Ledger Mapping', path: PATHS.TDS.LEDGER_MAPPING, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.ledger_mapping.view' },
            { id: 'tds-deduction-register', title: 'TDS Deduction Register', path: PATHS.TDS.DEDUCTIONS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.deduction_register.view' },
            { id: 'tds-payable-register', title: 'TDS Payable Register', path: PATHS.TDS.PAYABLE_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.payable_register.view' },
            { id: 'tds-challan', title: 'TDS Challan / Payment', path: PATHS.TDS.CHALLANS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.challan.view' },
            { id: 'tds-returns', title: 'TDS Return / Filing Data', path: PATHS.TDS.RETURNS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.returns.view' },
            { id: 'tds-reports', title: 'TDS Reports', path: PATHS.TDS.REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.reports.view' },
            { id: 'form-26as', title: '26AS Reconciliation', path: PATHS.FORM_26AS.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'tds.reports.view' },
        ],
    },
    {
        id: 'tcs',
        title: 'TCS',
        icon: 'ReceiptLongIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'tds',
        children: [
            { id: 'tcs-dashboard', title: 'TCS Dashboard', path: PATHS.TCS.DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.dashboard.view' },
            { id: 'tcs-master', title: 'TCS Master / Section Rates', path: PATHS.TCS.MASTER, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'tds.master.view' },
            { id: 'tcs-deductions', title: 'TCS Deduction Register', path: PATHS.TCS.DEDUCTIONS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'tds.deduction_register.view' },
            { id: 'tcs-challans', title: 'TCS Challan / Payment', path: PATHS.TCS.CHALLANS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'tds.challan.view' },
            { id: 'tcs-reports', title: 'TCS Reports', path: PATHS.TCS.REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'tds.reports.view' },
        ],
    },
    {
        id: 'gst-menu',
        title: 'GST',
        icon: 'AssessmentIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'gst',
        children: [
            { id: 'gstr1-export', title: 'GSTR-1 Compliance', path: PATHS.GST.GSTR1, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.gstr1.view' },
            { id: 'gstr3b-compliance', title: 'GSTR-3B Compliance', path: PATHS.GST.GSTR3B, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.gstr3b.view' },
            { id: 'gstr9-annual', title: 'GSTR-9 Annual Return', path: PATHS.GST.GSTR9, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.gstr3b.view' },
            { id: 'gst-reconciliation', title: '2A / 2B Reconciliation', path: PATHS.GST.RECONCILIATION, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.gst_reconciliation.view' },
            { id: 'itc-register', title: 'GST Inward & ITC Register', path: PATHS.GST.ITC_REGISTER, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.itc_register.view' },
            { id: 'gst-payable', title: 'GST Payable Summary', path: PATHS.GST.PAYABLE, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.gst_payable.view' },
            { id: 'hsn-summary', title: 'HSN Summary', path: PATHS.GST.HSN_SUMMARY, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.hsn_summary.view' },
            { id: 'gst-ledger', title: 'GST Ledger', path: PATHS.GST.LEDGER, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'gst.gst_ledger.view' },
        ]
    },
    {
        id: 'mis-reports',
        title: 'MIS Reports',
        icon: 'AssessmentIcon',
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER],
        permission: 'reports',
        children: [
            { id: 'mis-dashboard', title: 'MIS Dashboard', path: '/mis/dashboard', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'mis.dashboard.view' },
            { id: 'director-mis', title: 'Director MIS Dashboard', path: PATHS.MIS.DIRECTOR_DASHBOARD, roles: [ROLES.ADMIN], permission: 'mis.director_dashboard.view' },
            { id: 'sales-analysis', title: 'Sales MIS Dashboard', path: PATHS.MIS.SALES_DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'mis.sales_marketing.view' },
            { id: 'report-product-gp', title: 'Product-wise GP Analysis', path: PATHS.MIS.PRODUCT_GP, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'mis.product_gp_analysis.view' },
            { id: 'report-gp-analysis', title: 'GP Analysis Hub', path: PATHS.MIS.GP_ANALYSIS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'mis.product_gp_analysis.view' },
            { id: 'report-sample-conversion', title: 'Sample Conversion Analysis', path: PATHS.REPORTS.SAMPLE_CONVERSION, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports' },
            { id: 'report-replacements', title: 'Replacement Outward Report', path: PATHS.REPORTS.REPLACEMENTS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports' },
            { id: 'report-purchase-comparison', title: 'Purchase Comparison Report', path: '/reports/purchase-comparison', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports.purchase_comparison_report.view' },
        ]
    },
    {
        id: 'fixed-assets-parent',
        title: 'Fixed Assets',
        icon: 'AccountBalanceIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'accounts',
        children: [
            { id: 'fixed-assets-list', title: 'Asset Register', path: PATHS.FIXED_ASSETS.LIST, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'accounts.fixed_assets.view' },
            { id: 'asset-categories', title: 'Asset Categories', path: PATHS.FIXED_ASSETS.CATEGORIES, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.asset_categories.view' },
            { id: 'asset-locations', title: 'Asset Locations', path: PATHS.FIXED_ASSETS.LOCATIONS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.asset_locations.view' },
            { id: 'depreciation', title: 'Depreciation', path: PATHS.DEPRECIATION.ROOT, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.fixed_assets.view' },
            { id: 'depreciation-schedule', title: 'Depreciation Schedule', path: PATHS.DEPRECIATION.SCHEDULE, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'accounts.fixed_assets.view' },
        ]
    },
    {
        id: 'service',
        title: 'Service',
        icon: 'SettingsIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'service',
        children: [
            { id: 'complaints', title: 'Customer Complaints', path: PATHS.SERVICE.COMPLAINTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'service.complaints.view' },
            { id: 'replacement-dashboard', title: 'Replacement Dashboard', path: PATHS.SERVICE.REPLACEMENT_DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'service.replacement_dashboard.view' },
        ],
    },
    {
        id: 'prd',
        title: 'Product R&D',
        icon: 'ScienceIcon',
        roles: [ROLES.ADMIN, 'rd_manager', 'hardware_dev', 'firmware_dev', 'testing_eng', 'qa_head', 'production', 'management_viewer'],
        permission: 'prd',
        children: [
            { id: 'prd-dashboard', title: 'R&D Dashboard', path: PATHS.PRD.DASHBOARD, roles: [ROLES.ADMIN, 'rd_manager', 'hardware_dev', 'firmware_dev', 'testing_eng', 'qa_head', 'production', 'management_viewer'], permission: 'prd.dashboard.view' },
            { id: 'prd-projects', title: 'Product Development Master', path: PATHS.PRD.PROJECTS, roles: [ROLES.ADMIN, 'rd_manager', 'hardware_dev', 'firmware_dev', 'testing_eng', 'qa_head', 'production', 'management_viewer'], permission: 'prd.projects.view' },
            { id: 'prd-parameters', title: 'Test Parameter Master', path: PATHS.PRD.TEST_PARAMETERS, roles: [ROLES.ADMIN, 'rd_manager', 'qa_head'], permission: 'prd.test_parameters.view' },
        ],
    },
    {
        id: 'rd-samples',
        title: 'R&D Samples',
        icon: 'ScienceIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER],
        permission: 'rd_samples',
        children: [
            { id: 'rd-projects-samples', title: 'R&D Projects', path: '/rd-samples/projects', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'rd_samples.projects.view' },
            { id: 'rd-sample-list', title: 'Sample Tracker', path: '/rd-samples/samples', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'rd_samples.samples.view' },
            { id: 'rd-comparison', title: 'Sample Comparison', path: '/rd-samples/comparison', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'rd_samples.samples.compare' },
        ],
    },
    {
        id: 'china-supplier',
        title: 'China Sourcing',
        icon: 'GlobeIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        permission: 'wechat',
        children: [
            { id: 'cs-dashboard', title: 'Dashboard', path: PATHS.CHINA_SUPPLIER.DASHBOARD, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'wechat.contacts.view' },
            { id: 'cs-products', title: 'Products (R&D)', path: PATHS.CHINA_SUPPLIER.PRODUCTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'wechat.contacts.view' },
            { id: 'cs-contacts', title: 'Supplier Contacts', path: PATHS.CHINA_SUPPLIER.CONTACTS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'wechat.contacts.view' },
            { id: 'cs-groups', title: 'WeChat Groups', path: PATHS.CHINA_SUPPLIER.GROUPS, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'wechat.contacts.view' },
            { id: 'cs-prices', title: 'Price Comparison', path: PATHS.CHINA_SUPPLIER.PRICES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'wechat.contacts.view' },
            { id: 'cs-samples', title: 'Samples Tracking', path: PATHS.CHINA_SUPPLIER.SAMPLES, roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF], permission: 'wechat.contacts.view' },
            { id: 'cs-reports', title: 'Reports', path: PATHS.CHINA_SUPPLIER.REPORTS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'reports' },
        ],
    },
    {
        id: 'hr',
        title: 'HR Management',
        icon: 'BadgeIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER],
        permission: 'hr',
        children: [
            { id: 'hr-dashboard', title: 'HR Dashboard', path: '/hr/dashboard', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.hr_dashboard.view' },
            { id: 'employee-master', title: 'Employee Master', path: '/hr/employees', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.employee_master.view' },
            { id: 'shift-master', title: 'Shift Master', path: '/hr/shifts', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.shift_master.view' },
            { id: 'attendance', title: 'Attendance', path: '/hr/attendance', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.attendance.view' },
            { id: 'attendance-import', title: 'Attendance Import', path: '/hr/attendance/import', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.attendance.import' },
            { id: 'leave-management', title: 'Leave Management', path: '/hr/leaves', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.leave_management.view' },
            { id: 'payroll', title: 'Payroll / Salary Working', path: '/hr/payroll', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.payroll.view' },
            { id: 'hr-reports', title: 'HR Reports', path: '/hr/reports', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.hr_reports.view' },
            { id: 'holiday-list', title: 'Holiday List', path: '/hr/holidays', roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'hr.hr_reports.view' },
        ],
    },
    {
        id: 'communication-bulk-group',
        title: 'Communication',
        path: PATHS.SETTINGS.COMMUNICATION_HOME,
        icon: 'ChatIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER],
        permission: null,
        children: [
            { id: 'communication-email-settings', title: 'Platform Email Settings', path: PATHS.SETTINGS.EMAIL, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email.settings.view' },
            { id: 'communication-history', title: 'Communication History', path: PATHS.SETTINGS.COMMUNICATION_HISTORY, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email.communication_history.view' },
            { id: 'communication-email-bulk-campaigns', title: 'Email Bulk Message Utility', path: PATHS.SETTINGS.EMAIL_BULK.CAMPAIGNS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email_bulk.campaigns.view' },
            { id: 'communication-email-bulk-templates', title: 'Email Template Master', path: PATHS.SETTINGS.EMAIL_BULK.TEMPLATES, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email_bulk.templates.view' },
            { id: 'communication-email-bulk-blacklist', title: 'Email Blacklist', path: PATHS.SETTINGS.EMAIL_BULK.BLACKLIST, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email_bulk.blacklist.view' },
            { id: 'communication-email-bulk-history', title: 'Email Campaign History', path: PATHS.SETTINGS.EMAIL_BULK.HISTORY, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email_bulk.campaigns.view' },
            { id: 'communication-email-bulk-settings', title: 'Email Bulk Messaging Settings', path: PATHS.SETTINGS.EMAIL_BULK.SETTINGS, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'email_bulk.settings.view' },
        ],
    },
    {
        id: 'print-format-designer',
        title: 'Print Format Designer',
        icon: 'SettingsIcon',
        roles: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
        path: PATHS.SETTINGS.PRINT_FORMAT_DESIGNER,
        permission: 'admin.print_format_designer.view',
    },
    // Optional per-user UI customization (visible only when
    // ui.advancedCustomizationEnabled feature flag is on; defaults OFF).
    {
        id: 'ui-preferences',
        title: 'My UI Preferences',
        path: '/profile/ui-preferences',
        icon: 'SettingsIcon',
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.VIEWER],
        permission: null,
    },
    {
        id: 'admin',
        title: 'Admin',
        path: '/admin/home',
        icon: 'SettingsIcon',
        roles: [ROLES.ADMIN],
        permission: 'admin',
        children: [
            {
                id: 'admin-company-settings',
                title: 'Company Settings',
                roles: [ROLES.ADMIN],
                permission: 'admin',
                children: [
                    { id: 'company-profile', title: 'Company Profile', path: PATHS.SETTINGS.COMPANY_PROFILE, roles: [ROLES.ADMIN], permission: 'admin.company_profile.view' },
                ],
            },
            {
                id: 'admin-user-security',
                title: 'User & Security',
                roles: [ROLES.ADMIN],
                permission: 'admin',
                children: [
                    { id: 'user-management', title: 'User Management', path: '/admin/users', roles: [ROLES.ADMIN], permission: 'admin.user_management.view' },
                ],
            },
            {
                id: 'admin-configuration',
                title: 'Configuration',
                roles: [ROLES.ADMIN],
                permission: 'admin',
                children: [
                    { id: 'feature-compliance-settings', title: 'Feature Configuration Engine', path: PATHS.SETTINGS.FEATURE_COMPLIANCE, roles: [ROLES.ADMIN], permission: 'admin' },
                ],
            },
            {
                id: 'admin-utilities',
                title: 'Utilities',
                roles: [ROLES.ADMIN],
                permission: 'admin',
                children: [
                    { id: 'import-center', title: 'Import Center', path: PATHS.SETTINGS.IMPORT_CENTER, roles: [ROLES.ADMIN, ROLES.MANAGER], permission: 'import_utility.import_utility.view' },
                    { id: 'ledger-linking', title: 'Ledger Linking Utility', path: '/admin/ledger-linking', roles: [ROLES.ADMIN], permission: 'admin.ledger_linking.view' },
                ],
            },
        ],
    },
    // ── Super Admin / Platform (superadmin only — hidden via platformAccess) ─
    {
        id: 'super-admin',
        title: 'Super Admin',
        icon: 'SettingsIcon',
        path: PATHS.SAAS_ADMIN.HOME,
        roles: [ROLES.SUPERADMIN],
        permission: null,
        children: [
            {
                id: 'super-admin-saas',
                title: 'SaaS Admin',
                roles: [ROLES.SUPERADMIN],
                permission: null,
                children: [
                    { id: 'saas-dashboard', title: 'SaaS Dashboard', path: PATHS.SAAS_ADMIN.DASHBOARD, roles: [ROLES.SUPERADMIN], permission: null },
                    { id: 'saas-companies', title: 'Companies & Subscriptions', path: PATHS.SAAS_ADMIN.COMPANIES, roles: [ROLES.SUPERADMIN], permission: null },
                    { id: 'saas-subscriptions', title: 'Subscriptions', path: PATHS.SAAS_ADMIN.SUBSCRIPTIONS, roles: [ROLES.SUPERADMIN], permission: null },
                    { id: 'saas-activity', title: 'Activity Logs', path: PATHS.SAAS_ADMIN.ACTIVITY_LOGS, roles: [ROLES.SUPERADMIN], permission: null },
                ],
            },
            {
                id: 'super-admin-platform-setup',
                title: 'Platform Setup',
                roles: [ROLES.SUPERADMIN],
                permission: null,
                children: [
                    { id: 'industry-template-master', title: 'Industry Template Master', path: PATHS.SETTINGS.INDUSTRY_TEMPLATES, roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    { id: 'company-module-allocation', title: 'Company Module Allocation', path: PATHS.SETTINGS.COMPANY_MODULE_ALLOCATION, roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    { id: 'industry-deployment-manager', title: 'Industry Deployment Manager', path: PATHS.SETTINGS.INDUSTRY_DEPLOYMENT_MANAGER, roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    { id: 'platform-feature-defaults', title: 'Platform Default Settings', path: PATHS.SETTINGS.PLATFORM_FEATURE_DEFAULTS, roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    { id: 'workflow-master', title: 'Workflow Master', path: PATHS.SETTINGS.WORKFLOW_MASTER, roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    { id: 'print-format-version-manager', title: 'Print Format Version Manager', path: PATHS.SETTINGS.PRINT_FORMAT_VERSION_MANAGER, roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    // Print Format Designer moved to Admin → Configuration (permission-based for staff)
                ],
            },
            {
                id: 'super-admin-tenant',
                title: 'Tenant Management',
                roles: [ROLES.SUPERADMIN],
                permission: null,
                children: [
                    { id: 'companies-list', title: 'All Companies (Platform)', path: PATHS.SETTINGS.COMPANIES_LIST, roles: [ROLES.SUPERADMIN], permission: 'admin.company_profile.view' },
                ],
            },
            {
                id: 'super-admin-system',
                title: 'System',
                roles: [ROLES.SUPERADMIN],
                permission: null,
                children: [
                    { id: 'system-diagnostic', title: 'System Master Diagnostic', path: '/admin/diagnostics', roles: [ROLES.SUPERADMIN], permission: 'admin' },
                    { id: 'backup-restore', title: 'Backup & Restore', path: '/admin/backups', roles: [ROLES.SUPERADMIN], permission: 'admin' },
                ],
            },
        ],
    },
];

export const getFlattenedMenu = () => {
    const flattened = [];
    const traverse = (items) => {
        items.forEach(item => {
            const { children, ...rest } = item;
            flattened.push(rest);
            if (children && children.length > 0) {
                traverse(children);
            }
        });
    };
    traverse(menuConfig);
    return flattened;
};

