import React from 'react';
import ExpandableModuleHome from '@/features/dashboard/components/ExpandableModuleHome';
import {
    FileText,
    BookOpen,
    ShoppingBag,
    ShoppingCart,
    Receipt,
    CalendarDays,
    Wallet,
    Landmark,
    Scale,
    BarChart3,
    TrendingUp,
    PieChart,
    Percent,
    GitCompare,
    Hourglass,
    ShieldCheck,
    Activity,
    ArrowLeftRight,
    Building2,
    ScrollText,
    Lock,
    Settings2,
    Coins,
} from 'lucide-react';
import { PATHS } from '@/routes/paths';

const SESSION_SECTION_KEY = 'jsk.accountReportHome.expandedSection';

/** Leaf section helper — one card opens one existing report route. */
function leaf(section) {
    return {
        id: section.id,
        title: section.title,
        description: section.description,
        icon: section.icon,
        expandedHeading: section.title,
        moduleCode: section.moduleCode || 'accounts',
        tools: [
            {
                id: section.id,
                title: section.title,
                description: section.description,
                path: section.path,
                icon: section.icon,
                permission: section.permission,
                moduleCode: section.moduleCode || 'accounts',
            },
        ],
    };
}

const SECTIONS = [
    leaf({
        id: 'vouchers',
        title: 'Voucher Register',
        description: 'View voucher-wise accounting transactions and details.',
        path: PATHS.ACCOUNTS.VOUCHER_LIST,
        icon: FileText,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'ledger-report',
        title: 'Ledger Report',
        description: 'View ledger transactions, balances and movements.',
        path: PATHS.ACCOUNTS.LEDGER_REPORT,
        icon: BookOpen,
        permission: 'accounts.ledger_report.view',
    }),
    leaf({
        id: 'sales-register',
        title: 'Sales Register',
        description: 'View sales transactions and summaries.',
        path: PATHS.ACCOUNTS.SALES_REGISTER,
        icon: ShoppingBag,
        permission: 'accounts.sales_register.view',
    }),
    leaf({
        id: 'purchase-register',
        title: 'Purchase Register',
        description: 'View purchase transactions and summaries.',
        path: PATHS.ACCOUNTS.PURCHASE_REGISTER,
        icon: ShoppingCart,
        permission: 'accounts.purchase_register.view',
    }),
    leaf({
        id: 'expense-register',
        title: 'Expense Register',
        description: 'View expense vouchers and expense summaries.',
        path: PATHS.ACCOUNTS.EXPENSE_REGISTER,
        icon: Receipt,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'day-book',
        title: 'Day Book',
        description: 'View day-wise voucher activity.',
        path: PATHS.ACCOUNTS.DAY_BOOK,
        icon: CalendarDays,
        permission: 'accounts.day_book.view',
    }),
    leaf({
        id: 'cash-book',
        title: 'Cash Book',
        description: 'View cash receipts, payments and balances.',
        path: PATHS.ACCOUNTS.CASH_BOOK,
        icon: Wallet,
        permission: 'accounts.cash_book.view',
    }),
    leaf({
        id: 'bank-book',
        title: 'Bank Book',
        description: 'View bank receipts, payments and balances.',
        path: PATHS.ACCOUNTS.BANK_BOOK,
        icon: Landmark,
        permission: 'accounts.bank_book.view',
    }),
    leaf({
        id: 'bank-reconciliation',
        title: 'Bank Reconciliation',
        description: 'Reconcile bank statements with book balances.',
        path: PATHS.ACCOUNTS.BANK_RECONCILIATION,
        icon: Scale,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'outstanding',
        title: 'Outstanding Report',
        description: 'View receivable and payable outstanding.',
        path: PATHS.ACCOUNTS.OUTSTANDING_REPORT,
        icon: Hourglass,
        permission: 'accounts.outstanding.view',
    }),
    leaf({
        id: 'trial-balance-acc',
        title: 'Trial Balance',
        description: 'View account balances and trial balance summary.',
        path: '/mis/reports/trial-balance',
        icon: Scale,
        permission: 'mis.trial_balance.view',
    }),
    leaf({
        id: 'profit-loss-acc',
        title: 'Profit & Loss',
        description: 'View income, expenses and profitability.',
        path: '/mis/reports/profit-loss',
        icon: TrendingUp,
        permission: 'mis.profit_loss.view',
    }),
    leaf({
        id: 'balance-sheet-acc',
        title: 'Balance Sheet',
        description: 'View assets, liabilities and financial position.',
        path: '/mis/reports/balance-sheet',
        icon: PieChart,
        permission: 'mis.balance_sheet.view',
    }),
    leaf({
        id: 'interest-payable-statement',
        title: 'Interest Payable Statement',
        description: 'View interest payable calculations and statements.',
        path: PATHS.ACCOUNTS.INTEREST_PAYABLE,
        icon: Percent,
        permission: 'accounts.interest_payable_statement.view',
    }),
    leaf({
        id: 'cash-flow',
        title: 'Cash Flow Statement',
        description: 'View cash inflows and outflows.',
        path: PATHS.CASH_FLOW,
        icon: ArrowLeftRight,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'comparative-pl',
        title: 'Comparative P&L',
        description: 'Compare profit and loss across periods.',
        path: PATHS.COMPARATIVE_PL,
        icon: GitCompare,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'comparative-bs',
        title: 'Comparative Balance Sheet',
        description: 'Compare balance sheet across periods.',
        path: PATHS.COMPARATIVE_BS,
        icon: GitCompare,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'ageing-analysis',
        title: 'Ageing Analysis',
        description: 'View aged receivables and payables.',
        path: PATHS.AGEING,
        icon: Hourglass,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'msme-report',
        title: 'MSME Compliance Report',
        description: 'View MSME payment compliance status.',
        path: PATHS.MSME_REPORT,
        icon: ShieldCheck,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'ratio-analysis',
        title: 'Ratio Analysis',
        description: 'View key financial ratios and analysis.',
        path: PATHS.RATIO_ANALYSIS,
        icon: Activity,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'fund-flow',
        title: 'Fund Flow Statement',
        description: 'View sources and application of funds.',
        path: PATHS.FUND_FLOW,
        icon: BarChart3,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'cost-center-pl',
        title: 'Cost Centre P&L',
        description: 'View profit and loss by cost centre.',
        path: PATHS.COST_CENTERS.PL_REPORT,
        icon: Building2,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'accounting-audit',
        title: 'Accounting Audit Trail',
        description: 'View accounting change and audit history.',
        path: PATHS.ACCOUNTS.ACCOUNTING_AUDIT,
        icon: ScrollText,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'period-lock',
        title: 'Period Lock Settings',
        description: 'Lock or unlock accounting periods.',
        path: PATHS.ACCOUNTS.PERIOD_LOCK,
        icon: Lock,
        permission: 'accounts.vouchers.view',
    }),
    leaf({
        id: 'credit-note-ledger-config',
        title: 'Credit Note Ledger Config',
        description: 'Configure credit note ledger mapping.',
        path: PATHS.ACCOUNTS.CREDIT_NOTE_LEDGER_CONFIG,
        icon: Settings2,
        permission: 'accounts.ledger_master.edit',
    }),
    {
        id: 'petty-cash-group',
        title: 'Petty Cash',
        description: 'Petty cash entry, import, reports and settings.',
        icon: Coins,
        expandedHeading: 'Petty Cash Tools',
        moduleCode: 'accounts',
        tools: [
            {
                id: 'petty-cash-entry',
                title: 'Petty Cash Entry',
                description: 'Record petty cash vouchers.',
                path: PATHS.ACCOUNTS.PETTY_CASH_ENTRY,
                icon: Coins,
                permission: 'voucher_entry.petty_cash.view',
                moduleCode: 'accounts',
            },
            {
                id: 'petty-cash-import',
                title: 'Petty Cash Import',
                description: 'Import petty cash entries.',
                path: PATHS.ACCOUNTS.PETTY_CASH_IMPORT,
                icon: FileText,
                permission: 'voucher_entry.petty_cash.import',
                moduleCode: 'accounts',
            },
            {
                id: 'petty-cash-reports',
                title: 'Petty Cash Reports',
                description: 'View petty cash reports.',
                path: PATHS.ACCOUNTS.PETTY_CASH_REPORTS,
                icon: BarChart3,
                permission: 'voucher_entry.petty_cash.view',
                moduleCode: 'accounts',
            },
            {
                id: 'petty-cash-settings',
                title: 'Petty Cash Settings',
                description: 'Configure petty cash settings.',
                path: PATHS.ACCOUNTS.PETTY_CASH_SETTINGS,
                icon: Settings2,
                permission: 'voucher_entry.petty_cash.edit',
                moduleCode: 'accounts',
            },
        ],
    },
];

export default function AccountReportHomePage() {
    return (
        <ExpandableModuleHome
            title="Account Report - Home"
            subtitle="View accounting registers, books, outstanding and financial reports."
            sections={SECTIONS}
            sessionKey={SESSION_SECTION_KEY}
            dataComponent="account-report-home"
        />
    );
}
