/**
 * Central Permission Registry
 * Detailed submodule/action definitions for User Management.
 * Modules declared in moduleRegistry.constants.js are auto-added via permissionRegistryEnricher.js
 * when not listed here — add full submodule detail here when you need granular permissions.
 */

export const STANDARD_ACTIONS = [
    { id: 'view', label: 'View', type: 'boolean' },
    { id: 'add', label: 'Create', type: 'boolean' },
    { id: 'edit', label: 'Edit', type: 'boolean' },
    { id: 'delete', label: 'Delete', type: 'boolean' }
];

const EXTENDED_ACTIONS = [
    ...STANDARD_ACTIONS,
    { id: 'print', label: 'Print', type: 'boolean' },
    { id: 'export', label: 'Export', type: 'boolean' },
    { id: 'cancel', label: 'Cancel', type: 'boolean' },
    { id: 'approve', label: 'Approve', type: 'boolean' }
];

export const PERMISSION_REGISTRY = [
    {
        id: 'home',
        name: 'Home',
        submodules: [
            { id: 'dashboard', name: 'Home Page', actions: [{ id: 'view', label: 'View Home', type: 'boolean' }] },
            { id: 'add_form', name: 'Add Form', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'home_cards', name: 'Customize Home Cards', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Change Colour', type: 'boolean' }] },
            { id: 'theme', name: 'Customize Theme', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Change Theme', type: 'boolean' }] }
        ]
    },
    {
        id: 'customers',
        name: 'Customers',
        submodules: [
            { id: 'customer_master', name: 'Customer Master', actions: [...EXTENDED_ACTIONS, { id: 'import', label: 'Import', type: 'boolean' }] },
            {
                id: 'customer_documents',
                name: 'Customer Documents / KYC',
                actions: [
                    { id: 'view', label: 'View Customer Documents', type: 'boolean' },
                    { id: 'upload', label: 'Upload Customer Documents', type: 'boolean' },
                    { id: 'delete', label: 'Delete Customer Documents', type: 'boolean' },
                    { id: 'download', label: 'Download Customer Documents', type: 'boolean' },
                    { id: 'scan', label: 'Scan Customer Documents', type: 'boolean' },
                ],
            },
            { id: 'reminder_tasks', name: 'Reminder Tasks', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'follow_up', name: 'Follow-up Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'talk', label: 'Talk With Customer', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ],
    },
    {
        id: 'crm',
        name: 'CRM',
        submodules: [
            { id: 'customer_master', name: 'Customer Master', actions: [...EXTENDED_ACTIONS, { id: 'import', label: 'Import', type: 'boolean' }] },
            {
                id: 'customer_documents',
                name: 'Customer Documents / KYC',
                actions: [
                    { id: 'view', label: 'View Customer Documents', type: 'boolean' },
                    { id: 'upload', label: 'Upload Customer Documents', type: 'boolean' },
                    { id: 'delete', label: 'Delete Customer Documents', type: 'boolean' },
                    { id: 'download', label: 'Download Customer Documents', type: 'boolean' },
                    { id: 'scan', label: 'Scan Customer Documents', type: 'boolean' },
                ],
            },
            {
                id: 'leads',
                name: 'Inquiry / Lead',
                actions: [
                    { id: 'view', label: 'Lead View Own', type: 'boolean' },
                    { id: 'view_all', label: 'Lead View All', type: 'boolean' },
                    { id: 'add', label: 'Lead Create', type: 'boolean' },
                    { id: 'edit', label: 'Lead Edit Own', type: 'boolean' },
                    { id: 'edit_all', label: 'Lead Edit All', type: 'boolean' },
                    { id: 'delete', label: 'Delete', type: 'boolean' },
                    { id: 'assign', label: 'Lead Assign / Reassign', type: 'boolean' },
                    { id: 'report_view', label: 'Lead Report View Own', type: 'boolean' },
                    { id: 'report_view_all', label: 'Lead Report View All', type: 'boolean' },
                    { id: 'create_task', label: 'Lead Create Task', type: 'boolean' },
                    { id: 'convert_whatsapp', label: 'Convert WhatsApp Chat to Lead', type: 'boolean' },
                    { id: 'share_asset', label: 'Share Catalog / Datasheet', type: 'boolean' },
                ],
            },
            { id: 'product_catalog', name: 'Product Catalog', actions: [...STANDARD_ACTIONS, { id: 'share', label: 'Share to WhatsApp', type: 'boolean' }] },
            { id: 'follow_up', name: 'Follow-up Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'talk', label: 'Talk With Customer', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] }
        ]
    },
    {
        id: 'whatsapp',
        name: 'WhatsApp',
        submodules: [
            { id: 'whatsapp_settings', name: 'WhatsApp Settings & Chat', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
        ],
    },
    {
        id: 'whatsapp_bulk',
        name: 'WhatsApp Bulk Messaging',
        submodules: [
            { id: 'campaigns', name: 'WhatsApp Bulk Message Utility', actions: [...STANDARD_ACTIONS, { id: 'send', label: 'Send / Control Campaign', type: 'boolean' }, { id: 'export', label: 'Export History', type: 'boolean' }] },
            { id: 'matter_master', name: 'WhatsApp Matter Master', actions: STANDARD_ACTIONS },
            { id: 'blacklist', name: 'WhatsApp Blacklist', actions: STANDARD_ACTIONS },
            { id: 'history', name: 'Campaign History', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export History', type: 'boolean' }] },
            { id: 'settings', name: 'WhatsApp Bulk Messaging Settings', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'number_health', name: 'WhatsApp Number Health', actions: [
                { id: 'view', label: 'View Number Health', type: 'boolean' },
                { id: 'validate', label: 'Validate Numbers', type: 'boolean' },
                { id: 'lookup', label: 'WhatsApp Availability Lookup', type: 'boolean' },
                { id: 'export', label: 'Export Number Health', type: 'boolean' },
                { id: 'blacklist', label: 'Blacklist from Number Health', type: 'boolean' },
            ] },
            { id: 'report', name: 'WhatsApp Bulk Reports', actions: [
                { id: 'view', label: 'View Campaign Reports', type: 'boolean' },
                { id: 'export', label: 'Export Campaign Reports', type: 'boolean' },
            ] },
            { id: 'ai_assist', name: 'WhatsApp Bulk AI Assist', actions: [
                { id: 'view', label: 'View AI Assist', type: 'boolean' },
                { id: 'generate', label: 'Generate AI Draft', type: 'boolean' },
            ] },
        ],
    },
    {
        id: 'whatsapp_ai',
        name: 'WhatsApp AI',
        submodules: [
            { id: 'module', name: 'WhatsApp AI Access', actions: [
                { id: 'view', label: 'View WhatsApp AI', type: 'boolean' },
                { id: 'archive', label: 'Archive AI Records', type: 'boolean' },
                { id: 'takeover', label: 'Take Over Chat', type: 'boolean' },
                { id: 'return_to_ai', label: 'Return Chat to AI', type: 'boolean' },
            ] },
            { id: 'settings', name: 'AI Settings', actions: [{ id: 'manage', label: 'Manage AI Settings', type: 'boolean' }] },
            { id: 'knowledge', name: 'AI Knowledge', actions: [
                { id: 'manage', label: 'Manage Knowledge', type: 'boolean' },
                { id: 'approve', label: 'Approve Knowledge', type: 'boolean' },
            ] },
            { id: 'conversations', name: 'AI Conversations', actions: [
                { id: 'view_all', label: 'View All Conversations', type: 'boolean' },
                { id: 'view_assigned', label: 'View Assigned Conversations', type: 'boolean' },
            ] },
            { id: 'lead_draft', name: 'AI Lead Drafts', actions: [
                { id: 'create', label: 'Create Lead Draft', type: 'boolean' },
                { id: 'approve', label: 'Approve Lead Draft', type: 'boolean' },
            ] },
            { id: 'documents', name: 'AI Product Documents', actions: [
                { id: 'manage', label: 'Manage Documents', type: 'boolean' },
                { id: 'share', label: 'Share Documents', type: 'boolean' },
            ] },
            { id: 'audit', name: 'AI Audit Logs', actions: [{ id: 'view', label: 'View Audit Logs', type: 'boolean' }] },
            { id: 'dashboard', name: 'AI Dashboard', actions: [{ id: 'view', label: 'View Dashboard', type: 'boolean' }] },
            { id: 'testing', name: 'AI Testing', actions: [
                { id: 'inbound', label: 'Run Internal Inbound Test', type: 'boolean' },
                { id: 'generate_draft', label: 'Generate Internal Test Draft', type: 'boolean' },
            ] },
            { id: 'drafts', name: 'AI Reply Drafts', actions: [
                { id: 'view', label: 'View Reply Drafts', type: 'boolean' },
                { id: 'edit', label: 'Edit Reply Drafts', type: 'boolean' },
                { id: 'approve', label: 'Approve Reply Drafts', type: 'boolean' },
                { id: 'reject', label: 'Reject Reply Drafts', type: 'boolean' },
                { id: 'regenerate', label: 'Request Draft Regeneration', type: 'boolean' },
            ] },
        ],
    },
    {
        id: 'email',
        name: 'Platform Email',
        submodules: [
            { id: 'settings', name: 'Platform Email Settings', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }, { id: 'test', label: 'Test Connection', type: 'boolean' }] },
            { id: 'communication_history', name: 'Communication History', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ],
    },
    {
        id: 'email_bulk',
        name: 'Email Bulk Messaging',
        submodules: [
            { id: 'campaigns', name: 'Email Bulk Message Utility', actions: [...STANDARD_ACTIONS, { id: 'send', label: 'Send / Control Campaign', type: 'boolean' }, { id: 'export', label: 'Export History', type: 'boolean' }] },
            { id: 'templates', name: 'Email Template Master', actions: STANDARD_ACTIONS },
            { id: 'blacklist', name: 'Email Blacklist', actions: STANDARD_ACTIONS },
            { id: 'history', name: 'Email Campaign History', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export History', type: 'boolean' }] },
            { id: 'settings', name: 'Email Bulk Messaging Settings', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
        ],
    },
    {
        id: 'tasks',
        name: 'Task Management',
        submodules: [
            { id: 'task_list', name: 'Manage Tasks', actions: STANDARD_ACTIONS },
            { id: 'task_groups', name: 'Task Groups', actions: [
                ...STANDARD_ACTIONS,
                { id: 'manage', label: 'Manage Items', type: 'boolean' },
                { id: 'highlight', label: 'Highlight Groups', type: 'boolean' },
                { id: 'reorder_highlights', label: 'Reorder Highlights', type: 'boolean' },
                { id: 'manage_members', label: 'Manage Members', type: 'boolean' },
                { id: 'manage_tasks', label: 'Manage Group Tasks', type: 'boolean' },
                { id: 'complete_shared_task', label: 'Complete Shared Group Task', type: 'boolean' },
            ] },
            { id: 'reminders', name: 'Reminders', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] }
        ]
    },
    {
        id: 'reports',
        name: 'General Reports',
        submodules: [
            { id: 'customer_master_report', name: 'Customer Master Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            {
                id: 'customer_kyc_reports',
                name: 'Customer KYC / Document Reports',
                actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }],
            },
            {
                id: 'supplier_kyc_reports',
                name: 'Supplier KYC / Document Reports',
                actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }],
            },
            { id: 'followup_report', name: 'Follow-up Tracker Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'followup_dashboard_report', name: 'Follow-up Dashboard Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'followup_task_report', name: 'Follow-up Task Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'conversation_history_report', name: 'Conversation History', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'task_reminder_report', name: 'Task Reminder Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'lead_report', name: 'Lead Report', actions: [{ id: 'view', label: 'View Own', type: 'boolean' }, { id: 'view_all', label: 'View All', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'reminder_report', name: 'Open Reminders Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }] }
        ]
    },
    {
        id: 'sales',
        name: 'Sales',
        submodules: [
            { id: 'sales_orders', name: 'Sales Orders', actions: EXTENDED_ACTIONS },
            {
                id: 'sales_invoices',
                name: 'Tax Invoice GST',
                actions: [
                    { id: 'view', label: 'View', type: 'boolean' },
                    { id: 'add', label: 'Create', type: 'boolean' },
                    { id: 'edit', label: 'Edit', type: 'boolean' },
                    { id: 'delete', label: 'Sales Invoice Delete', type: 'boolean' },
                    { id: 'print', label: 'Print', type: 'boolean' },
                    { id: 'export', label: 'Export', type: 'boolean' },
                    { id: 'cancel', label: 'Sales Invoice Cancel', type: 'boolean' },
                    { id: 'approve', label: 'Approve', type: 'boolean' },
                    { id: 'whatsapp', label: 'WhatsApp Send', type: 'boolean' },
                    { id: 'email', label: 'Email Send', type: 'boolean' },
                ],
            },
            {
                id: 'internal_sales',
                name: 'Estimate / Internal Sale',
                actions: [
                    { id: 'view', label: 'View Estimates', type: 'boolean' },
                    { id: 'add', label: 'Create Estimate', type: 'boolean' },
                    { id: 'edit', label: 'Edit Estimate', type: 'boolean' },
                    { id: 'delete', label: 'Estimate Delete', type: 'boolean' },
                    { id: 'print', label: 'Print', type: 'boolean' },
                    { id: 'export', label: 'Export', type: 'boolean' },
                    { id: 'cancel', label: 'Cancel Estimate', type: 'boolean' },
                    { id: 'approve', label: 'Approve', type: 'boolean' },
                ],
            },
            { id: 'eway_bills', name: 'E-Way Bill Tracking', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'invoice_series', name: 'Invoice Series', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'logistics', name: 'Logistics & Courier Master', actions: STANDARD_ACTIONS }
        ]
    },
    {
        id: 'purchase',
        name: 'Purchase',
        submodules: [
            { id: 'purchase_orders', name: 'Purchase Order', actions: EXTENDED_ACTIONS },
            { id: 'purchase_invoices', name: 'Purchase Invoice', actions: EXTENDED_ACTIONS },
            { id: 'suppliers', name: 'Supplier Master', actions: [...STANDARD_ACTIONS, { id: 'export', label: 'Export', type: 'boolean' }] },
            {
                id: 'supplier_documents',
                name: 'Supplier Documents / KYC',
                actions: [
                    { id: 'view', label: 'View Supplier Documents', type: 'boolean' },
                    { id: 'upload', label: 'Upload Supplier Documents', type: 'boolean' },
                    { id: 'delete', label: 'Delete Supplier Documents', type: 'boolean' },
                    { id: 'download', label: 'Download Supplier Documents', type: 'boolean' },
                    { id: 'scan', label: 'Scan Supplier Documents', type: 'boolean' },
                ],
            },
            { id: 'grn', name: 'Goods Receipt (GRN)', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }, { id: 'print', label: 'Print', type: 'boolean' }] },
            { id: 'purchase_rfq', name: 'Purchase RFQ', actions: [...STANDARD_ACTIONS, { id: 'cancel', label: 'Cancel', type: 'boolean' }] },
            { id: 'supplier_quotation', name: 'Supplier Quotation Entry', actions: STANDARD_ACTIONS },
            { id: 'quotation_comparison', name: 'Quotation Comparison', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit Selection', type: 'boolean' }] },
            { id: 'quotation_approve', name: 'Quotation Approve', actions: [{ id: 'approve', label: 'Approve', type: 'boolean' }] },
            { id: 'convert_rfq_to_po', name: 'Convert RFQ to Purchase Order', actions: [{ id: 'add', label: 'Convert', type: 'boolean' }] },
        ]
    },
    {
        id: 'documents',
        name: 'Documents',
        submodules: [
            { id: 'scan_bills', name: 'Scan Bills', actions: [...STANDARD_ACTIONS, { id: 'scan', label: 'Scan & Attach', type: 'boolean' }] },
            { id: 'missing_attachments', name: 'Missing Attachments Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ]
    },
    {
        id: 'inventory',
        name: 'Inventory',
        submodules: [
            { id: 'item_master', name: 'Item Master', actions: [...STANDARD_ACTIONS, { id: 'export', label: 'Export', type: 'boolean' }, { id: 'import', label: 'Import', type: 'boolean' }] },
            { id: 'item_types', name: 'Item Types', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'item_groups', name: 'Item Groups', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'item_images', name: 'Item Images (Textile)', actions: [
                { id: 'view', label: 'View', type: 'boolean' },
                { id: 'upload', label: 'Upload', type: 'boolean' },
                { id: 'delete', label: 'Delete', type: 'boolean' },
                { id: 'download', label: 'Download', type: 'boolean' },
            ] },
            { id: 'bom', name: 'BOM (Bill of Materials)', actions: [...EXTENDED_ACTIONS] },
            { id: 'raw_material_report', name: 'Raw Material Stock Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'finished_goods_report', name: 'Finished Goods Stock Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'stock_ledger', name: 'Stock Movement Ledger', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] }
        ]
    },
    {
        id: 'production',
        name: 'Production',
        submodules: [
            { id: 'prod_dashboard', name: 'Production Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'work_orders', name: 'Work Order', actions: EXTENDED_ACTIONS },
            { id: 'production_entry', name: 'Production Entry', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'model_conversion', name: 'Model Conversion', actions: EXTENDED_ACTIONS },
            { id: 'comp_replacement', name: 'Component Replacement', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'prod_rejection', name: 'Production Rejection', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'prod_rework', name: 'Failure & Rework', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'production_planning', name: 'Production Planning / MRP', actions: [...STANDARD_ACTIONS, { id: 'calculate', label: 'Calculate', type: 'boolean' }, { id: 'approve', label: 'Approve', type: 'boolean' }] },
            { id: 'workflow_production', name: 'Workflow Production', actions: EXTENDED_ACTIONS },
            { id: 'textile_production', name: 'Textile / Handloom Production', actions: EXTENDED_ACTIONS },
            { id: 'textile_job_work_rates', name: 'Textile Job Work Rate Master', actions: EXTENDED_ACTIONS },
            { id: 'textile_conversion', name: 'Textile Conversion & Transformation', actions: EXTENDED_ACTIONS },
            { id: 'textile_dyeing_challan', name: 'Textile Dyeing Challan & Return', actions: EXTENDED_ACTIONS },
            { id: 'textile_process_route', name: 'Textile Process Route Master', actions: EXTENDED_ACTIONS },
            { id: 'textile_production_workflow', name: 'Textile Production Workflow', actions: EXTENDED_ACTIONS }
        ]
    },
    {
        id: 'voucher_entry',
        name: 'Voucher Entry',
        submodules: [
            { id: 'receipt_entry', name: 'Receipt Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }, { id: 'print', label: 'Print', type: 'boolean' }] },
            { id: 'payment_entry', name: 'Payment Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }, { id: 'print', label: 'Print', type: 'boolean' }] },
            { id: 'journal_entry', name: 'Journal Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'expense_entry', name: 'Expense Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'petty_cash', name: 'Petty Cash', actions: [...STANDARD_ACTIONS, { id: 'import', label: 'Import', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }, { id: 'approve', label: 'Approve Import', type: 'boolean' }] },
            { id: 'debit_notes', name: 'Debit Note', actions: EXTENDED_ACTIONS },
            { id: 'credit_notes', name: 'Credit Note', actions: EXTENDED_ACTIONS },
            {
                id: 'bill_adjustment',
                name: 'Bill Adjustment / Credit Notes',
                actions: [
                    { id: 'view_note_balance', label: 'View Credit Note Balance', type: 'boolean' },
                    { id: 'use_credit_note', label: 'Apply Credit Note to Invoice', type: 'boolean' },
                    { id: 'reverse_note_allocation', label: 'Reverse Credit Note Allocation', type: 'boolean' },
                ],
            },
        ]
    },
    {
        id: 'account_master',
        name: 'Account Master',
        submodules: [
            { id: 'group_master', name: 'Group Master', actions: STANDARD_ACTIONS },
            { id: 'ledger_master', name: 'Ledger Master', actions: STANDARD_ACTIONS },
            { id: 'financial_year', name: 'Financial Year Master', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'series_master', name: 'Series Master', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] }
        ]
    },
    {
        id: 'accounts_reports',
        name: 'Accounts',
        submodules: [
            { id: 'vouchers', name: 'Voucher Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'ledger_report', name: 'Ledger Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'sales_register', name: 'Sales Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'purchase_register', name: 'Purchase Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'expense_register', name: 'Expense Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'day_book', name: 'Day Book', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'cash_book', name: 'Cash Book', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'bank_book', name: 'Bank Book', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'outstanding', name: 'Outstanding Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] }
        ]
    },
    {
        id: 'tds',
        name: 'TDS',
        submodules: [
            { id: 'dashboard', name: 'TDS Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'master', name: 'TDS Master / Section Rates', actions: STANDARD_ACTIONS },
            { id: 'ledger_mapping', name: 'TDS Ledger Mapping', actions: STANDARD_ACTIONS },
            { id: 'deduction_register', name: 'TDS Deduction Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'payable_register', name: 'TDS Payable Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'challan', name: 'TDS Challan / Payment', actions: [...STANDARD_ACTIONS] },
            { id: 'returns', name: 'TDS Return / Filing Data', actions: [...STANDARD_ACTIONS, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'reports', name: 'TDS Reports', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'settings', name: 'TDS Settings', actions: STANDARD_ACTIONS },
        ],
    },
    {
        id: 'gst',
        name: 'GST',
        submodules: [
            { id: 'gstr1', name: 'GSTR-1', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'gstr3b', name: 'GSTR-3B', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'gst_reconciliation', name: '2A / 2B Reconciliation', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'import', label: 'Import', type: 'boolean' }] },
            { id: 'gst_payable', name: 'GST Payable Summary', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'itc_register', name: 'ITC Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'hsn_summary', name: 'HSN Summary', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'gst_ledger', name: 'GST Ledger', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ]
    },
    {
        id: 'mis',
        name: 'MIS Reports',
        submodules: [
            { id: 'dashboard', name: 'Sales MIS Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'sales_marketing', name: 'Sales & Marketing MIS', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'director_dashboard', name: 'Director MIS Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'product_gp', name: 'Product-wise GP Analysis', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'sales_conversion', name: 'Sales Conversion Analysis Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] }
        ]
    },
    {
        id: 'scan_entry',
        name: 'Scan Entry',
        submodules: [
            {
                id: 'scan_entry',
                name: 'Scan Entry / Invoice Import',
                actions: [
                    { id: 'view', label: 'View', type: 'boolean' },
                    { id: 'upload', label: 'Upload', type: 'boolean' },
                    { id: 'review', label: 'Review', type: 'boolean' },
                    { id: 'post', label: 'Post', type: 'boolean' },
                    { id: 'reject', label: 'Reject', type: 'boolean' },
                    { id: 'delete', label: 'Delete', type: 'boolean' },
                    { id: 'admin_override_duplicate', label: 'Override Duplicate', type: 'boolean' },
                ],
            },
        ],
    },
    {
        id: 'import_utility',
        name: 'AI Smart Import Utility',
        submodules: [
            {
                id: 'import_utility',
                name: 'Import Utility / Scan Entry',
                actions: [
                    { id: 'view', label: 'View', type: 'boolean' },
                    { id: 'upload', label: 'Upload', type: 'boolean' },
                    { id: 'review', label: 'Review', type: 'boolean' },
                    { id: 'approve_post', label: 'Approve / Post', type: 'boolean' },
                    { id: 'reject', label: 'Reject', type: 'boolean' },
                    { id: 'duplicate_override', label: 'Duplicate Override', type: 'boolean' },
                    { id: 'create_draft_ledger', label: 'Create Draft Ledger', type: 'boolean' },
                    { id: 'approve_ledger', label: 'Approve Ledger', type: 'boolean' },
                    { id: 'create_draft_item', label: 'Create Draft Item', type: 'boolean' },
                    { id: 'map_item', label: 'Map Item', type: 'boolean' },
                    { id: 'delete', label: 'Delete', type: 'boolean' },
                ],
            },
        ],
    },
    {
        id: 'data_extractor',
        name: 'Data Extractor / Market Finder',
        submodules: [
            {
                id: 'extractor',
                name: 'Data Extractor',
                actions: [
                    { id: 'view', label: 'View', type: 'boolean' },
                    { id: 'search', label: 'Search / Extract', type: 'boolean' },
                    { id: 'import', label: 'Import Excel/CSV', type: 'boolean' },
                    { id: 'export', label: 'Export', type: 'boolean' },
                    { id: 'approve', label: 'Approve / Reject', type: 'boolean' },
                    { id: 'convert_lead', label: 'Convert to Lead', type: 'boolean' },
                    { id: 'convert_supplier', label: 'Convert to Supplier', type: 'boolean' },
                    { id: 'convert_customer', label: 'Convert to Customer', type: 'boolean' },
                    { id: 'delete', label: 'Delete Draft', type: 'boolean' },
                    { id: 'settings', label: 'Manage Settings', type: 'boolean' },
                ],
            },
            {
                id: 'discovery',
                name: 'Business Discovery',
                actions: [
                    { id: 'view', label: 'View Discovery', type: 'boolean' },
                    { id: 'create', label: 'Create Discovery Job', type: 'boolean' },
                    { id: 'run', label: 'Run Discovery', type: 'boolean' },
                    { id: 'pause', label: 'Pause Discovery', type: 'boolean' },
                    { id: 'stop', label: 'Stop Discovery', type: 'boolean' },
                    { id: 'resume', label: 'Resume Discovery', type: 'boolean' },
                    { id: 'export', label: 'Export Discovery Results', type: 'boolean' },
                    { id: 'approve', label: 'Approve / Reject Discovery', type: 'boolean' },
                    { id: 'convert_lead', label: 'Convert Discovery to Lead', type: 'boolean' },
                    { id: 'convert_customer', label: 'Convert Discovery to Customer', type: 'boolean' },
                    { id: 'convert_supplier', label: 'Convert Discovery to Supplier', type: 'boolean' },
                    { id: 'settings', label: 'Discovery Settings', type: 'boolean' },
                    { id: 'delete_draft', label: 'Delete Discovery Draft', type: 'boolean' },
                    { id: 'use_local_agent', label: 'Use Local Discovery Agent', type: 'boolean' },
                ],
            },
            {
                id: 'search_campaign',
                name: 'Search Campaign',
                actions: [
                    { id: 'view', label: 'View Search Campaigns', type: 'boolean' },
                    { id: 'manage', label: 'Manage Search Campaigns', type: 'boolean' },
                ],
            },
            {
                id: 'search_query',
                name: 'Search Query',
                actions: [
                    { id: 'view', label: 'View Search Queries', type: 'boolean' },
                    { id: 'manage', label: 'Manage Search Queries', type: 'boolean' },
                    { id: 'generate', label: 'Generate Search Queries', type: 'boolean' },
                    { id: 'review', label: 'Review Search Queries', type: 'boolean' },
                    { id: 'open', label: 'Open Search Queries', type: 'boolean' },
                ],
            },
            {
                id: 'raw_capture',
                name: 'Raw Capture',
                actions: [
                    { id: 'view', label: 'View Raw Captures', type: 'boolean' },
                    { id: 'ingest', label: 'Ingest Raw Captures', type: 'boolean' },
                    { id: 'import', label: 'Import Raw Captures (URL/Text/CSV/Excel)', type: 'boolean' },
                    { id: 'manage', label: 'Manage Raw Captures', type: 'boolean' },
                    { id: 'archive', label: 'Archive Raw Captures', type: 'boolean' },
                ],
            },
            {
                id: 'assisted_capture',
                name: 'Assisted Capture',
                actions: [
                    { id: 'view', label: 'View Assisted Captures', type: 'boolean' },
                    { id: 'start', label: 'Start Assisted Captures', type: 'boolean' },
                    { id: 'manage', label: 'Manage Assisted Captures', type: 'boolean' },
                ],
            },
            {
                id: 'lead_intelligence',
                name: 'AI Lead Intelligence',
                actions: [
                    { id: 'view', label: 'View AI Lead Intelligence', type: 'boolean' },
                    { id: 'manage', label: 'Manage AI Masters', type: 'boolean' },
                    { id: 'classify', label: 'Run AI Classification', type: 'boolean' },
                    { id: 'batch', label: 'Batch Classification', type: 'boolean' },
                    { id: 'override', label: 'Override Classification', type: 'boolean' },
                    { id: 'lock', label: 'Lock Classification', type: 'boolean' },
                    { id: 'mark_irrelevant', label: 'Mark Irrelevant', type: 'boolean' },
                    { id: 'view_evidence', label: 'View Evidence', type: 'boolean' },
                    { id: 'view_history', label: 'View Classification History', type: 'boolean' },
                    { id: 'audit', label: 'View AI Audit Trail', type: 'boolean' },
                    { id: 'relevance_run', label: 'Run Lead Relevance Scoring', type: 'boolean' },
                    { id: 'relevance_exclude', label: 'Exclude Low-Relevance Leads', type: 'boolean' },
                    { id: 'relevance_restore', label: 'Restore Excluded Leads', type: 'boolean' },
                    { id: 'relevance_audit', label: 'View Relevance Audit History', type: 'boolean' },
                ],
            },
            {
                id: 'product_recommendation',
                name: 'Product Opportunity Recommendation',
                actions: [
                    { id: 'view', label: 'View Product Recommendations', type: 'boolean' },
                    { id: 'run', label: 'Run Product Recommendations', type: 'boolean' },
                    { id: 'override', label: 'Override Recommendations', type: 'boolean' },
                    { id: 'lock', label: 'Lock Recommendations', type: 'boolean' },
                    { id: 'history', label: 'View Recommendation History', type: 'boolean' },
                    { id: 'audit', label: 'View Recommendation Audit', type: 'boolean' },
                    { id: 'manage', label: 'Manage Product Master', type: 'boolean' },
                ],
            },
            {
                id: 'contact_intelligence',
                name: 'Contact Intelligence',
                actions: [
                    { id: 'view', label: 'View Contact Intelligence', type: 'boolean' },
                    { id: 'run', label: 'Run Contact Analysis', type: 'boolean' },
                    { id: 'batch', label: 'Batch Contact Analysis', type: 'boolean' },
                    { id: 'override', label: 'Override Contact Analysis', type: 'boolean' },
                    { id: 'verify', label: 'Verify Contacts', type: 'boolean' },
                    { id: 'merge', label: 'Merge Duplicate Contacts', type: 'boolean' },
                    { id: 'lock', label: 'Lock Contact Intelligence', type: 'boolean' },
                    { id: 'history', label: 'View Contact History', type: 'boolean' },
                    { id: 'audit', label: 'View Contact Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Approved Contacts', type: 'boolean' },
                    { id: 'manage', label: 'Manage Contact Role Master', type: 'boolean' },
                ],
            },
            {
                id: 'company_intelligence',
                name: 'Company Intelligence Profile',
                actions: [
                    { id: 'view', label: 'View Company Intelligence', type: 'boolean' },
                    { id: 'generate', label: 'Generate Company Profiles', type: 'boolean' },
                    { id: 'batch', label: 'Batch Profile Generation', type: 'boolean' },
                    { id: 'edit', label: 'Edit Company Profiles', type: 'boolean' },
                    { id: 'approve', label: 'Approve Company Profiles', type: 'boolean' },
                    { id: 'lock', label: 'Lock Company Profiles', type: 'boolean' },
                    { id: 'history', label: 'View Profile History', type: 'boolean' },
                    { id: 'audit', label: 'View Profile Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Approved Profiles', type: 'boolean' },
                    { id: 'manage', label: 'Manage Company Intelligence Settings', type: 'boolean' },
                ],
            },
            {
                id: 'lead_scoring',
                name: 'Lead Scoring and Priority',
                actions: [
                    { id: 'view', label: 'View Lead Scores', type: 'boolean' },
                    { id: 'run', label: 'Run Lead Scoring', type: 'boolean' },
                    { id: 'batch', label: 'Batch Lead Scoring', type: 'boolean' },
                    { id: 'override', label: 'Override Lead Scores', type: 'boolean' },
                    { id: 'approve', label: 'Approve Lead Scores', type: 'boolean' },
                    { id: 'reject', label: 'Reject Lead Scores', type: 'boolean' },
                    { id: 'lock', label: 'Lock Lead Scores', type: 'boolean' },
                    { id: 'history', label: 'View Lead Score History', type: 'boolean' },
                    { id: 'audit', label: 'View Lead Score Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Approved Lead Scores', type: 'boolean' },
                    { id: 'manage', label: 'Manage Lead Scoring Settings', type: 'boolean' },
                ],
            },
            {
                id: 'similar_company',
                name: 'Similar Company Discovery',
                actions: [
                    { id: 'view', label: 'View Similar Companies', type: 'boolean' },
                    { id: 'run', label: 'Run Similar Company Analysis', type: 'boolean' },
                    { id: 'batch', label: 'Batch Similar Company Analysis', type: 'boolean' },
                    { id: 'override', label: 'Override Similar Company Results', type: 'boolean' },
                    { id: 'approve', label: 'Approve Candidates for Enrichment', type: 'boolean' },
                    { id: 'reject', label: 'Reject Similar Company Candidates', type: 'boolean' },
                    { id: 'lock', label: 'Lock Similar Company Results', type: 'boolean' },
                    { id: 'history', label: 'View Similar Company History', type: 'boolean' },
                    { id: 'audit', label: 'View Similar Company Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Approved Candidates', type: 'boolean' },
                    { id: 'manage', label: 'Manage Similar Company Settings', type: 'boolean' },
                ],
            },
            {
                id: 'market_intelligence',
                name: 'Market Intelligence',
                actions: [
                    { id: 'view', label: 'View Market Intelligence', type: 'boolean' },
                    { id: 'run', label: 'Run Market Intelligence', type: 'boolean' },
                    { id: 'manage', label: 'Manage Market Intelligence', type: 'boolean' },
                ],
            },
            {
                id: 'crm_enrichment',
                name: 'CRM Enrichment and Lead Draft',
                actions: [
                    { id: 'view', label: 'View CRM Enrichment', type: 'boolean' },
                    { id: 'match', label: 'Match CRM Records', type: 'boolean' },
                    { id: 'prepare', label: 'Prepare Enrichment Drafts', type: 'boolean' },
                    { id: 'review', label: 'Review Enrichment Fields', type: 'boolean' },
                    { id: 'create_lead', label: 'Create CRM Lead from Draft', type: 'boolean' },
                    { id: 'apply', label: 'Apply CRM Enrichment', type: 'boolean' },
                    { id: 'batch', label: 'Batch Enrichment Preparation', type: 'boolean' },
                    { id: 'rollback', label: 'Rollback Enrichment', type: 'boolean' },
                    { id: 'lock', label: 'Lock Enrichment Reviews', type: 'boolean' },
                    { id: 'history', label: 'View Enrichment History', type: 'boolean' },
                    { id: 'audit', label: 'View Enrichment Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Enrichment Audit', type: 'boolean' },
                    { id: 'manage', label: 'Manage CRM Enrichment Settings', type: 'boolean' },
                ],
            },
            {
                id: 'sales_workflow',
                name: 'Sales Assignment and Follow-up Workflow',
                actions: [
                    { id: 'view', label: 'View Sales Workflow', type: 'boolean' },
                    { id: 'recommend', label: 'Recommend Salespersons', type: 'boolean' },
                    { id: 'prepare', label: 'Prepare Assignment Drafts', type: 'boolean' },
                    { id: 'review', label: 'Review Assignment and Follow-up', type: 'boolean' },
                    { id: 'assign', label: 'Apply Lead Assignment', type: 'boolean' },
                    { id: 'reassign', label: 'Reassign Lead Owner', type: 'boolean' },
                    { id: 'create_task', label: 'Create Approved Tasks', type: 'boolean' },
                    { id: 'create_followup', label: 'Create Approved Follow-ups', type: 'boolean' },
                    { id: 'batch_prepare', label: 'Batch Prepare Recommendations', type: 'boolean' },
                    { id: 'batch_apply', label: 'Batch Apply Assignments', type: 'boolean' },
                    { id: 'rollback', label: 'Rollback Assignment Actions', type: 'boolean' },
                    { id: 'lock', label: 'Lock Sales Workflow Drafts', type: 'boolean' },
                    { id: 'history', label: 'View Sales Workflow History', type: 'boolean' },
                    { id: 'audit', label: 'View Sales Workflow Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Sales Workflow Audit', type: 'boolean' },
                    { id: 'manage', label: 'Manage Sales Workflow Settings', type: 'boolean' },
                ],
            },
            {
                id: 'analytics',
                name: 'Executive Analytics and Monitoring',
                actions: [
                    { id: 'view', label: 'View Analytics', type: 'boolean' },
                    { id: 'executive', label: 'Executive Summary', type: 'boolean' },
                    { id: 'discovery', label: 'Discovery Analytics', type: 'boolean' },
                    { id: 'lead_intelligence', label: 'Lead Intelligence Analytics', type: 'boolean' },
                    { id: 'product', label: 'Product Opportunity Analytics', type: 'boolean' },
                    { id: 'contact', label: 'Contact Analytics', type: 'boolean' },
                    { id: 'market', label: 'Market Analytics', type: 'boolean' },
                    { id: 'crm_conversion', label: 'CRM Conversion Analytics', type: 'boolean' },
                    { id: 'sales_workflow', label: 'Sales Workflow Analytics', type: 'boolean' },
                    { id: 'batch_monitor', label: 'Batch Monitor', type: 'boolean' },
                    { id: 'user_activity', label: 'User Activity Analytics', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'manage_views', label: 'Manage Company Views', type: 'boolean' },
                    { id: 'refresh', label: 'Refresh Snapshots', type: 'boolean' },
                    { id: 'export', label: 'Export Analytics', type: 'boolean' },
                    { id: 'audit', label: 'View Analytics Audit', type: 'boolean' },
                    { id: 'manage', label: 'Manage Analytics Settings', type: 'boolean' },
                ],
            },
            {
                id: 'marketing_intelligence',
                name: 'Campaign and Marketing Intelligence',
                actions: [
                    { id: 'view', label: 'View Marketing Intelligence', type: 'boolean' },
                    { id: 'create', label: 'Create Campaign Drafts', type: 'boolean' },
                    { id: 'build_audience', label: 'Build Audience', type: 'boolean' },
                    { id: 'review_recipients', label: 'Review Recipients', type: 'boolean' },
                    { id: 'review_duplicates', label: 'Review Duplicates', type: 'boolean' },
                    { id: 'review_optout', label: 'Review Opt-out / Blacklist', type: 'boolean' },
                    { id: 'generate_message', label: 'Generate Message Draft', type: 'boolean' },
                    { id: 'edit_message', label: 'Edit Message Draft', type: 'boolean' },
                    { id: 'approve_audience', label: 'Approve Audience', type: 'boolean' },
                    { id: 'approve_message', label: 'Approve Message', type: 'boolean' },
                    { id: 'approve_content', label: 'Approve Content', type: 'boolean' },
                    { id: 'approve_handoff', label: 'Approve Handoff', type: 'boolean' },
                    { id: 'prepare_handoff', label: 'Prepare Handoff Package', type: 'boolean' },
                    { id: 'batch', label: 'Batch Prepare', type: 'boolean' },
                    { id: 'lock', label: 'Lock Campaign Drafts', type: 'boolean' },
                    { id: 'history', label: 'View Campaign History', type: 'boolean' },
                    { id: 'audit', label: 'View Marketing Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Campaign Draft', type: 'boolean' },
                    { id: 'manage', label: 'Manage Marketing Settings', type: 'boolean' },
                ],
            },
            {
                id: 'ai_sales_assistant',
                name: 'AI Sales Assistant (Read-Only)',
                actions: [
                    { id: 'view', label: 'View Sales Assistant', type: 'boolean' },
                    { id: 'ask', label: 'Ask Questions', type: 'boolean' },
                    { id: 'executive', label: 'Executive Questions', type: 'boolean' },
                    { id: 'sales', label: 'Sales Questions', type: 'boolean' },
                    { id: 'market', label: 'Market Questions', type: 'boolean' },
                    { id: 'contact', label: 'Contact Questions', type: 'boolean' },
                    { id: 'product', label: 'Product Questions', type: 'boolean' },
                    { id: 'crm_conversion', label: 'CRM Conversion Questions', type: 'boolean' },
                    { id: 'sales_workflow', label: 'Sales Workflow Questions', type: 'boolean' },
                    { id: 'marketing', label: 'Marketing Questions', type: 'boolean' },
                    { id: 'data_quality', label: 'Data Quality Questions', type: 'boolean' },
                    { id: 'batch_monitor', label: 'Batch Monitor Questions', type: 'boolean' },
                    { id: 'company_research', label: 'Company Research', type: 'boolean' },
                    { id: 'saved_prompts', label: 'Saved Prompts', type: 'boolean' },
                    { id: 'manage_prompts', label: 'Manage Shared Prompts', type: 'boolean' },
                    { id: 'export', label: 'Export Assistant Results', type: 'boolean' },
                    { id: 'history', label: 'View Query History', type: 'boolean' },
                    { id: 'audit', label: 'View Assistant Audit', type: 'boolean' },
                    { id: 'manage', label: 'Manage Assistant Settings', type: 'boolean' },
                ],
            },
            {
                id: 'knowledge_graph',
                name: 'Business Knowledge Graph',
                actions: [
                    { id: 'view', label: 'View Knowledge Graph', type: 'boolean' },
                    { id: 'search', label: 'Search Knowledge Graph', type: 'boolean' },
                    { id: 'relationships', label: 'View Relationships', type: 'boolean' },
                    { id: 'analytics', label: 'Graph Analytics', type: 'boolean' },
                    { id: 'export', label: 'Export Knowledge Graph', type: 'boolean' },
                    { id: 'manage', label: 'Manage / Discover Graph', type: 'boolean' },
                ],
            },
            {
                id: 'ai_learning',
                name: 'Learning Intelligence (Feedback)',
                actions: [
                    { id: 'view', label: 'View Learning Intelligence', type: 'boolean' },
                    { id: 'submit_feedback', label: 'Submit Feedback', type: 'boolean' },
                    { id: 'review_feedback', label: 'Review Feedback', type: 'boolean' },
                    { id: 'resolve_conflict', label: 'Resolve Conflicts', type: 'boolean' },
                    { id: 'analytics', label: 'View Analytics', type: 'boolean' },
                    { id: 'review_queue', label: 'Review Queue', type: 'boolean' },
                    { id: 'generate_proposal', label: 'Generate Draft Proposals', type: 'boolean' },
                    { id: 'review_proposal', label: 'Review Proposals', type: 'boolean' },
                    { id: 'export', label: 'Export Feedback / Datasets', type: 'boolean' },
                    { id: 'dataset', label: 'Prepare Evaluation Datasets', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'audit', label: 'View Learning Audit', type: 'boolean' },
                    { id: 'settings', label: 'Learning Settings', type: 'boolean' },
                    { id: 'manage', label: 'Manage Learning Intelligence', type: 'boolean' },
                ],
            },
            {
                id: 'improvement_approval',
                name: 'Improvement Approval Center',
                actions: [
                    { id: 'view', label: 'View Approval Center', type: 'boolean' },
                    { id: 'submit', label: 'Submit Approval Cases', type: 'boolean' },
                    { id: 'business_review', label: 'Business Review', type: 'boolean' },
                    { id: 'technical_review', label: 'Technical Review', type: 'boolean' },
                    { id: 'risk_review', label: 'Risk Review', type: 'boolean' },
                    { id: 'privacy_review', label: 'Privacy Review', type: 'boolean' },
                    { id: 'security_review', label: 'Security Review', type: 'boolean' },
                    { id: 'request_evidence', label: 'Request More Evidence', type: 'boolean' },
                    { id: 'approve', label: 'Final Approve for Spec', type: 'boolean' },
                    { id: 'reject', label: 'Reject Proposals', type: 'boolean' },
                    { id: 'generate_spec', label: 'Generate Implementation Spec', type: 'boolean' },
                    { id: 'export', label: 'Export Approval Data', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'audit', label: 'View Approval Audit', type: 'boolean' },
                    { id: 'settings', label: 'Approval Policy Settings', type: 'boolean' },
                    { id: 'manage', label: 'Manage Approval Center', type: 'boolean' },
                ],
            },
            {
                id: 'configuration_manager',
                name: 'Intelligence Configuration Manager',
                actions: [
                    { id: 'view', label: 'View Configuration Manager', type: 'boolean' },
                    { id: 'view_payload', label: 'View Configuration Payload', type: 'boolean' },
                    { id: 'create_draft', label: 'Create Draft Versions', type: 'boolean' },
                    { id: 'edit_draft', label: 'Edit Draft Versions', type: 'boolean' },
                    { id: 'clone', label: 'Clone Versions', type: 'boolean' },
                    { id: 'validate', label: 'Validate Versions', type: 'boolean' },
                    { id: 'compare', label: 'Compare Versions', type: 'boolean' },
                    { id: 'dependencies', label: 'View Dependencies', type: 'boolean' },
                    { id: 'compatibility', label: 'Check Compatibility', type: 'boolean' },
                    { id: 'review', label: 'Review Versions', type: 'boolean' },
                    { id: 'ready_for_sandbox', label: 'Mark Ready for Sandbox', type: 'boolean' },
                    { id: 'export', label: 'Export Sandbox Package', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'audit', label: 'View Configuration Audit', type: 'boolean' },
                    { id: 'settings', label: 'Configuration Manager Settings', type: 'boolean' },
                    { id: 'manage', label: 'Manage Configuration Manager', type: 'boolean' },
                ],
            },
            {
                id: 'sandbox_evaluation',
                name: 'Sandbox Evaluation',
                actions: [
                    { id: 'view', label: 'View Sandbox Evaluation', type: 'boolean' },
                    { id: 'create', label: 'Create Evaluation Runs', type: 'boolean' },
                    { id: 'validate', label: 'Validate Evaluation Runs', type: 'boolean' },
                    { id: 'run', label: 'Start Evaluation Runs', type: 'boolean' },
                    { id: 'cancel', label: 'Cancel Evaluation Runs', type: 'boolean' },
                    { id: 'view_results', label: 'View Evaluation Results', type: 'boolean' },
                    { id: 'view_row_detail', label: 'View Result Row Detail', type: 'boolean' },
                    { id: 'compare', label: 'A/B Compare', type: 'boolean' },
                    { id: 'export', label: 'Export Evaluation', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'audit', label: 'View Sandbox Audit', type: 'boolean' },
                    { id: 'settings', label: 'Sandbox Evaluation Settings', type: 'boolean' },
                    { id: 'manage', label: 'Manage Sandbox Evaluation', type: 'boolean' },
                ],
            },
            {
                id: 'release_manager',
                name: 'Release Management Center',
                actions: [
                    { id: 'view', label: 'View Release Manager', type: 'boolean' },
                    { id: 'create', label: 'Create Release Packages', type: 'boolean' },
                    { id: 'edit_draft', label: 'Edit Draft Releases', type: 'boolean' },
                    { id: 'validate', label: 'Validate Release Plans', type: 'boolean' },
                    { id: 'simulate', label: 'Run Deployment Simulation', type: 'boolean' },
                    { id: 'review', label: 'Technical/Development Review', type: 'boolean' },
                    { id: 'qa_review', label: 'QA Review', type: 'boolean' },
                    { id: 'security_review', label: 'Security Review', type: 'boolean' },
                    { id: 'database_review', label: 'Database Review', type: 'boolean' },
                    { id: 'business_review', label: 'Business Review', type: 'boolean' },
                    { id: 'industry_review', label: 'Industry Review', type: 'boolean' },
                    { id: 'release_review', label: 'Release Manager Review', type: 'boolean' },
                    { id: 'approve_staging_plan', label: 'Approve Staging Plan', type: 'boolean' },
                    { id: 'approve_pilot_plan', label: 'Approve Pilot Plan', type: 'boolean' },
                    { id: 'approve_production_plan', label: 'Approve Future Production Plan', type: 'boolean' },
                    { id: 'feature_flags', label: 'Feature Flag Plans', type: 'boolean' },
                    { id: 'backup_plan', label: 'Backup Plans', type: 'boolean' },
                    { id: 'rollback_plan', label: 'Rollback Plans', type: 'boolean' },
                    { id: 'migration_plan', label: 'Migration Plans', type: 'boolean' },
                    { id: 'export', label: 'Export Release Packages', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'audit', label: 'View Release Audit', type: 'boolean' },
                    { id: 'settings', label: 'Release Manager Settings', type: 'boolean' },
                    { id: 'manage', label: 'Manage Release Manager', type: 'boolean' },
                ],
            },
            {
                id: 'readiness_certification',
                name: 'Production Readiness Certification',
                actions: [
                    { id: 'view', label: 'View Readiness Certification', type: 'boolean' },
                    { id: 'create', label: 'Create Certifications', type: 'boolean' },
                    { id: 'define_scope', label: 'Define Certification Scope', type: 'boolean' },
                    { id: 'collect_evidence', label: 'Collect Evidence', type: 'boolean' },
                    { id: 'run_local_checks', label: 'Run Local Readiness Checks', type: 'boolean' },
                    { id: 'security_review', label: 'Security Review', type: 'boolean' },
                    { id: 'permission_review', label: 'Permission Review', type: 'boolean' },
                    { id: 'tenant_review', label: 'Tenant Isolation Review', type: 'boolean' },
                    { id: 'industry_review', label: 'Industry Review', type: 'boolean' },
                    { id: 'database_review', label: 'Database Review', type: 'boolean' },
                    { id: 'performance_review', label: 'Performance Review', type: 'boolean' },
                    { id: 'qa_review', label: 'QA Review', type: 'boolean' },
                    { id: 'continuity_review', label: 'Business Continuity Review', type: 'boolean' },
                    { id: 'create_finding', label: 'Create Findings', type: 'boolean' },
                    { id: 'review_finding', label: 'Review Findings', type: 'boolean' },
                    { id: 'create_remediation', label: 'Create Remediation', type: 'boolean' },
                    { id: 'retest', label: 'Retest Findings', type: 'boolean' },
                    { id: 'accept_risk', label: 'Accept Risk', type: 'boolean' },
                    { id: 'final_review', label: 'Final Readiness Review', type: 'boolean' },
                    { id: 'export', label: 'Export Certification Report', type: 'boolean' },
                    { id: 'saved_views', label: 'Saved Views', type: 'boolean' },
                    { id: 'audit', label: 'View Readiness Audit', type: 'boolean' },
                    { id: 'settings', label: 'Readiness Certification Settings', type: 'boolean' },
                    { id: 'manage', label: 'Manage Readiness Certification', type: 'boolean' },
                ],
            },
            {
                id: 'pilot',
                name: 'Controlled Pilot & UAT Center',
                actions: [
                    { id: 'view', label: 'View Pilot Center', type: 'boolean' },
                    { id: 'create', label: 'Create Pilot Programs', type: 'boolean' },
                    { id: 'update', label: 'Update Pilot Programs', type: 'boolean' },
                    { id: 'manage', label: 'Manage Pilot Center', type: 'boolean' },
                    { id: 'review', label: 'Pilot Review', type: 'boolean' },
                    { id: 'final_review', label: 'Final Pilot Review', type: 'boolean' },
                    { id: 'company_selection', label: 'Pilot Company Selection', type: 'boolean' },
                    { id: 'industry_selection', label: 'Pilot Industry Selection', type: 'boolean' },
                    { id: 'cohort_manage', label: 'Manage Pilot Cohorts', type: 'boolean' },
                    { id: 'module_plan', label: 'Module Allocation Plans', type: 'boolean' },
                    { id: 'feature_flag_plan', label: 'Feature Flag Plans', type: 'boolean' },
                    { id: 'uat.view', label: 'View UAT', type: 'boolean' },
                    { id: 'uat.manage', label: 'Manage UAT', type: 'boolean' },
                    { id: 'uat.execute', label: 'Execute UAT', type: 'boolean' },
                    { id: 'uat.review', label: 'Review UAT', type: 'boolean' },
                    { id: 'defect.view', label: 'View Defects', type: 'boolean' },
                    { id: 'defect.manage', label: 'Manage Defects', type: 'boolean' },
                    { id: 'risk.view', label: 'View Risks', type: 'boolean' },
                    { id: 'risk.manage', label: 'Manage Risks', type: 'boolean' },
                    { id: 'accept_risk', label: 'Accept Pilot Risk', type: 'boolean' },
                    { id: 'feedback.view', label: 'View Feedback', type: 'boolean' },
                    { id: 'feedback.manage', label: 'Manage Feedback', type: 'boolean' },
                    { id: 'evidence.view', label: 'View Evidence', type: 'boolean' },
                    { id: 'evidence.manage', label: 'Manage Evidence', type: 'boolean' },
                    { id: 'pause_review', label: 'Pause Review', type: 'boolean' },
                    { id: 'suspension_review', label: 'Suspension Review', type: 'boolean' },
                    { id: 'rollback_plan', label: 'Rollback Readiness Plans', type: 'boolean' },
                    { id: 'settings', label: 'Pilot Settings', type: 'boolean' },
                    { id: 'audit', label: 'View Pilot Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Pilot Reports', type: 'boolean' },
                    { id: 'saved_views', label: 'Pilot Saved Views', type: 'boolean' },
                ],
            },
            {
                id: 'operations',
                name: 'Enterprise Operations Center',
                actions: [
                    { id: 'view', label: 'View Operations Center', type: 'boolean' },
                    { id: 'create', label: 'Create Operations Programs', type: 'boolean' },
                    { id: 'update', label: 'Update Operations Programs', type: 'boolean' },
                    { id: 'manage', label: 'Manage Operations Center', type: 'boolean' },
                    { id: 'review', label: 'Operations Review', type: 'boolean' },
                    { id: 'final_review', label: 'Final Operations Review', type: 'boolean' },
                    { id: 'release_board', label: 'Release Governance Board', type: 'boolean' },
                    { id: 'production_plan', label: 'Production Control Plans', type: 'boolean' },
                    { id: 'environment_inventory', label: 'Environment Inventory', type: 'boolean' },
                    { id: 'release_calendar', label: 'Release Calendar', type: 'boolean' },
                    { id: 'maintenance_window', label: 'Maintenance Windows', type: 'boolean' },
                    { id: 'change.view', label: 'View Changes', type: 'boolean' },
                    { id: 'change.manage', label: 'Manage Changes', type: 'boolean' },
                    { id: 'emergency_change', label: 'Emergency Change Planning', type: 'boolean' },
                    { id: 'checklist.view', label: 'View Checklists', type: 'boolean' },
                    { id: 'checklist.manage', label: 'Manage Checklists', type: 'boolean' },
                    { id: 'monitoring.view', label: 'View Monitoring Plans', type: 'boolean' },
                    { id: 'monitoring.manage', label: 'Manage Monitoring Plans', type: 'boolean' },
                    { id: 'incident.view', label: 'View Incidents', type: 'boolean' },
                    { id: 'incident.manage', label: 'Manage Incidents', type: 'boolean' },
                    { id: 'problem.view', label: 'View Problems', type: 'boolean' },
                    { id: 'problem.manage', label: 'Manage Problems', type: 'boolean' },
                    { id: 'risk.view', label: 'View Operational Risks', type: 'boolean' },
                    { id: 'risk.manage', label: 'Manage Operational Risks', type: 'boolean' },
                    { id: 'accept_risk', label: 'Accept Operational Risk', type: 'boolean' },
                    { id: 'backup_plan', label: 'Backup Verification Plans', type: 'boolean' },
                    { id: 'restore_plan', label: 'Restore Verification Plans', type: 'boolean' },
                    { id: 'dr_plan', label: 'Disaster Recovery Plans', type: 'boolean' },
                    { id: 'rollback_plan', label: 'Rollback Authorization Plans', type: 'boolean' },
                    { id: 'communication', label: 'Communication Plans', type: 'boolean' },
                    { id: 'release_notes', label: 'Release Notes', type: 'boolean' },
                    { id: 'phase27_recommendation', label: 'Phase 27 Recommendation', type: 'boolean' },
                    { id: 'audit', label: 'View Operations Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Operations Reports', type: 'boolean' },
                    { id: 'saved_views', label: 'Operations Saved Views', type: 'boolean' },
                    { id: 'settings', label: 'Operations Settings', type: 'boolean' },
                ],
            },
            {
                id: 'activation_readiness',
                name: 'Production Activation Readiness',
                actions: [
                    { id: 'view', label: 'View Activation Readiness', type: 'boolean' },
                    { id: 'create', label: 'Create Readiness Programs', type: 'boolean' },
                    { id: 'update', label: 'Update Readiness Programs', type: 'boolean' },
                    { id: 'manage', label: 'Manage Activation Readiness', type: 'boolean' },
                    { id: 'validate', label: 'Validate Readiness', type: 'boolean' },
                    { id: 'review', label: 'Review Readiness', type: 'boolean' },
                    { id: 'final_review', label: 'Final Readiness Review', type: 'boolean' },
                    { id: 'release_lineage', label: 'Release Lineage Validation', type: 'boolean' },
                    { id: 'integrity_review', label: 'Release Integrity Review', type: 'boolean' },
                    { id: 'defect_gate', label: 'Defect Gate', type: 'boolean' },
                    { id: 'risk_gate', label: 'Risk Gate', type: 'boolean' },
                    { id: 'approvals', label: 'Approval Completeness', type: 'boolean' },
                    { id: 'environment_review', label: 'Environment Metadata Review', type: 'boolean' },
                    { id: 'maintenance_review', label: 'Maintenance Window Review', type: 'boolean' },
                    { id: 'monitoring_review', label: 'Monitoring Readiness Review', type: 'boolean' },
                    { id: 'incident_review', label: 'Incident Readiness Review', type: 'boolean' },
                    { id: 'backup_review', label: 'Backup Plan Review', type: 'boolean' },
                    { id: 'restore_review', label: 'Restore Plan Review', type: 'boolean' },
                    { id: 'rollback_review', label: 'Rollback Plan Review', type: 'boolean' },
                    { id: 'dr_review', label: 'Disaster Recovery Review', type: 'boolean' },
                    { id: 'communication_review', label: 'Communication Readiness Review', type: 'boolean' },
                    { id: 'customer_impact', label: 'Customer Impact Review', type: 'boolean' },
                    { id: 'hypercare', label: 'Hypercare Readiness Review', type: 'boolean' },
                    { id: 'smoke_test_plan', label: 'Smoke Test Plan', type: 'boolean' },
                    { id: 'manual_checklist', label: 'Manual Deployment Checklist', type: 'boolean' },
                    { id: 'handover', label: 'Deployment Handover Package', type: 'boolean' },
                    { id: 'exceptions', label: 'Readiness Exceptions', type: 'boolean' },
                    { id: 'recommendation', label: 'Readiness Recommendation', type: 'boolean' },
                    { id: 'audit', label: 'View Readiness Audit', type: 'boolean' },
                    { id: 'export', label: 'Export Readiness Reports', type: 'boolean' },
                    { id: 'saved_views', label: 'Readiness Saved Views', type: 'boolean' },
                    { id: 'settings', label: 'Readiness Settings', type: 'boolean' },
                ],
            },
        ],
    },
    {
        id: 'messenger',
        name: 'Messenger',
        submodules: [
            { id: 'module_access', name: 'Messenger Access', actions: [...STANDARD_ACTIONS, { id: 'send', label: 'Send Messages', type: 'boolean' }] },
        ],
    },
    {
        id: 'service',
        name: 'Service / Complaints',
        submodules: [
            { id: 'complaints', name: 'Customer Complaints', actions: [...STANDARD_ACTIONS, { id: 'assign', label: 'Assign', type: 'boolean' }] },
            { id: 'replacement_dashboard', name: 'Replacement Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'replacement_dispatches', name: 'Replacement Dispatches', actions: STANDARD_ACTIONS },
        ],
    },
    {
        id: 'wechat',
        name: 'China Sourcing / WeChat',
        submodules: [
            { id: 'contacts', name: 'Supplier Contacts & Groups', actions: [...STANDARD_ACTIONS, { id: 'import', label: 'Import', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'samples', name: 'Samples Tracking', actions: STANDARD_ACTIONS },
            { id: 'reports', name: 'China Sourcing Reports', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ],
    },
    {
        id: 'hr',
        name: 'HR / Payroll',
        submodules: [
            { id: 'hr_dashboard', name: 'HR Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'employee_master', name: 'Employee Master', actions: STANDARD_ACTIONS },
            { id: 'shift_master', name: 'Shift Master', actions: STANDARD_ACTIONS },
            { id: 'attendance', name: 'Attendance', actions: [...STANDARD_ACTIONS, { id: 'import', label: 'Import', type: 'boolean' }] },
            { id: 'leave_management', name: 'Leave Management', actions: STANDARD_ACTIONS },
            { id: 'payroll', name: 'Payroll / Salary Working', actions: [...STANDARD_ACTIONS, { id: 'approve', label: 'Approve', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'hr_reports', name: 'HR Reports', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ],
    },
    {
        id: 'prd',
        name: 'R&D / PRD',
        submodules: [
            { id: 'dashboard', name: 'R&D Dashboard', actions: [{ id: 'view', label: 'View', type: 'boolean' }] },
            { id: 'projects', name: 'Product Development Master', actions: EXTENDED_ACTIONS },
            { id: 'test_parameters', name: 'Test Parameter Master', actions: STANDARD_ACTIONS },
        ],
    },
    {
        id: 'rd_samples',
        name: 'R&D Samples',
        submodules: [
            { id: 'projects', name: 'R&D Projects', actions: STANDARD_ACTIONS },
            { id: 'samples', name: 'Sample Tracker', actions: [...STANDARD_ACTIONS, { id: 'compare', label: 'Compare Samples', type: 'boolean' }] },
        ],
    },
    {
        id: 'accounts',
        name: 'Accounts / Vouchers',
        submodules: [
            { id: 'receipt_entry', name: 'Receipt Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }, { id: 'print', label: 'Print', type: 'boolean' }] },
            { id: 'payment_entry', name: 'Payment Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }, { id: 'print', label: 'Print', type: 'boolean' }] },
            { id: 'journal_entry', name: 'Journal Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'expense_entry', name: 'Expense Voucher', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Add', type: 'boolean' }] },
            { id: 'credit_notes', name: 'Credit Note', actions: EXTENDED_ACTIONS },
            { id: 'debit_notes', name: 'Debit Note', actions: EXTENDED_ACTIONS },
            {
                id: 'bill_adjustment',
                name: 'Bill Adjustment / Credit Notes',
                actions: [
                    { id: 'view_note_balance', label: 'View Credit Note Balance', type: 'boolean' },
                    { id: 'use_credit_note', label: 'Apply Credit Note to Invoice', type: 'boolean' },
                    { id: 'reverse_note_allocation', label: 'Reverse Credit Note Allocation', type: 'boolean' },
                ],
            },
            { id: 'vouchers', name: 'Voucher Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'group_master', name: 'Group Master', actions: STANDARD_ACTIONS },
            { id: 'ledger_master', name: 'Ledger Master', actions: STANDARD_ACTIONS },
            { id: 'financial_year', name: 'Financial Year Master', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'manage', label: 'Manage', type: 'boolean' }] },
            { id: 'ledger_report', name: 'Ledger Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'sales_register', name: 'Sales Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'purchase_register', name: 'Purchase Register', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'day_book', name: 'Day Book', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'cash_book', name: 'Cash Book', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'bank_book', name: 'Bank Book', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'outstanding', name: 'Outstanding Report', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
            { id: 'fixed_assets', name: 'Fixed Assets Register', actions: EXTENDED_ACTIONS },
            { id: 'asset_categories', name: 'Asset Categories', actions: STANDARD_ACTIONS },
            { id: 'asset_locations', name: 'Asset Locations', actions: STANDARD_ACTIONS },
            { id: 'interest_payable_statement', name: 'Interest Payable Statement', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'export', label: 'Export', type: 'boolean' }] },
        ],
    },
    {
        id: 'admin',
        name: 'Admin',
        submodules: [
            { id: 'user_management', name: 'User Management', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'add', label: 'Create User', type: 'boolean' }, { id: 'edit', label: 'Edit User', type: 'boolean' }, { id: 'delete', label: 'Delete User', type: 'boolean' }, { id: 'password', label: 'Change Password', type: 'boolean' }, { id: 'rights', label: 'Manage Rights', type: 'boolean' }] },
            { id: 'role_management', name: 'Role Management', actions: STANDARD_ACTIONS },
            { id: 'security_control', name: 'Security & Control', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Manage', type: 'boolean' }, { id: 'approve', label: 'Approve', type: 'boolean' }] },
            { id: 'ledger_linking', name: 'Ledger Linking Utility', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'apply', label: 'Apply Linking', type: 'boolean' }] },
            { id: 'company_settings', name: 'Company Settings', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'company_profile', name: 'Company Profile', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'print_format_designer', name: 'Print Format Designer', actions: [{ id: 'view', label: 'Allow Print Format Designer', type: 'boolean' }] },
            { id: 'feature_configuration', name: 'Feature Configuration Engine', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'module_allocation', name: 'Company Module Allocation', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'industry_deployment_manager', name: 'Industry Deployment Manager', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'industry_templates', name: 'Industry Template Master', actions: STANDARD_ACTIONS },
            { id: 'platform_feature_defaults', name: 'Platform Default Settings', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] },
            { id: 'system_settings', name: 'System Settings', actions: [{ id: 'view', label: 'View', type: 'boolean' }, { id: 'edit', label: 'Edit', type: 'boolean' }] }
        ]
    }
];
