/**
 * Platform draft RCM rules (Phase 2A).
 * Loaded in-memory so localhost works without creating a new Mongo collection
 * (Atlas free tier may be at collection limit).
 * Status remains draft/inactive until owner activates via DB overlay later.
 */
export const PLATFORM_DRAFT_RCM_RULES = [
    {
        _id: 'seed-rent-commercial-ur',
        ruleCode: 'RENT_COMMERCIAL_UR_RECIPIENT_REG',
        category: 'RENT',
        title: 'Commercial rent from unregistered supplier to registered recipient (DRAFT)',
        serviceGoodsType: 'SERVICES',
        effectiveFrom: new Date('2017-07-01'),
        effectiveTo: null,
        supplierRegistrationCondition: ['Unregistered'],
        recipientRegistrationCondition: ['Registered'],
        propertyTypeCondition: ['Commercial'],
        transportServiceTypeCondition: [],
        supplierTaxOptionCondition: [],
        hsnSacCondition: [],
        placeOfSupplyCondition: [],
        consignmentNoteRequired: false,
        supplierGstChargedCondition: 'NO',
        decisionIfMatched: 'REVERSE_CHARGE',
        ratePercent: 18,
        requiredQuestions: ['propertyType', 'supplierGstCharged'],
        statutoryReference: 'CGST Act — renting of immovable property (draft seed; verify before activation)',
        status: 'draft',
        version: 1,
        notes: 'Phase 2A draft only. Do not treat as activated law.',
    },
    {
        _id: 'seed-gta-consignment',
        ruleCode: 'GTA_CONSIGNMENT_RECIPIENT_LIABLE',
        category: 'GTA',
        title: 'GTA with consignment note — recipient liable (DRAFT)',
        serviceGoodsType: 'SERVICES',
        effectiveFrom: new Date('2017-07-01'),
        effectiveTo: null,
        supplierRegistrationCondition: [],
        recipientRegistrationCondition: ['Registered'],
        propertyTypeCondition: [],
        transportServiceTypeCondition: ['GTA with consignment note'],
        supplierTaxOptionCondition: ['Reverse Charge', 'Transaction-wise', ''],
        hsnSacCondition: [],
        placeOfSupplyCondition: [],
        consignmentNoteRequired: true,
        supplierGstChargedCondition: 'ANY',
        decisionIfMatched: 'REVERSE_CHARGE',
        ratePercent: 5,
        requiredQuestions: ['transportServiceType', 'consignmentNoteAvailable'],
        statutoryReference: 'GTA reverse charge (draft seed; verify before activation)',
        status: 'draft',
        version: 1,
        notes: 'Courier is a separate category — do not use this for courier.',
    },
    {
        _id: 'seed-courier-not-gta',
        ruleCode: 'COURIER_NOT_GTA',
        category: 'COURIER',
        title: 'Courier / parcel — not automatic GTA RCM (DRAFT)',
        serviceGoodsType: 'SERVICES',
        effectiveFrom: new Date('2017-07-01'),
        effectiveTo: null,
        supplierRegistrationCondition: [],
        recipientRegistrationCondition: [],
        propertyTypeCondition: [],
        transportServiceTypeCondition: ['Courier', 'Parcel service'],
        supplierTaxOptionCondition: [],
        hsnSacCondition: [],
        placeOfSupplyCondition: [],
        consignmentNoteRequired: false,
        supplierGstChargedCondition: 'ANY',
        decisionIfMatched: 'FORWARD_CHARGE',
        ratePercent: 18,
        requiredQuestions: ['transportServiceType'],
        statutoryReference: 'Courier is not GTA merely by transport ledger (draft seed)',
        status: 'draft',
        version: 1,
        notes: 'Ensures courier does not inherit GTA RCM.',
    },
    {
        _id: 'seed-local-vehicle',
        ruleCode: 'LOCAL_VEHICLE_HIRE_REVIEW',
        category: 'OTHER',
        title: 'Local vehicle hire — independent review (DRAFT)',
        serviceGoodsType: 'SERVICES',
        effectiveFrom: new Date('2017-07-01'),
        effectiveTo: null,
        supplierRegistrationCondition: [],
        recipientRegistrationCondition: [],
        propertyTypeCondition: [],
        transportServiceTypeCondition: ['Local vehicle hire'],
        supplierTaxOptionCondition: [],
        hsnSacCondition: [],
        placeOfSupplyCondition: [],
        consignmentNoteRequired: false,
        supplierGstChargedCondition: 'ANY',
        decisionIfMatched: 'REVIEW_REQUIRED',
        ratePercent: null,
        requiredQuestions: ['transportServiceType', 'supplierGstCharged'],
        statutoryReference: 'Local hire is not automatic GTA (draft seed)',
        status: 'draft',
        version: 1,
        notes: '',
    },
];
